# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_business_address` (`ADDR_NUM` STRING, `TITLE` STRING, `NAME1` STRING, `CITY1` STRING, `POST_CODE1` STRING, `STR_SUPPL1` STRING, `LOCATION` STRING, `COUNTRY_KEY` STRING, `TEL_NUM` STRING, `ADDR_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_BUSINESS_ADDRESS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_PF_MIS_TARGET_FORMAT_PROD_KPI` (`PARTICULARS` string,`UOM` string,`KPI` string,`STAGE` string,`TARGET` decimal(13,6),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_MIS_TARGET_FORMAT_PROD_KPI'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_custom_incoterms` (`INCO1` STRING, `INCOTERMS` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_CUSTOM_INCOTERMS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_customer` (`CUST_ID` STRING, `COUNTRY` STRING, `NAME1` STRING, `NAME2` STRING, `CITY` STRING, `POSTAL_CODE` STRING, `REGION` STRING,`TELF_NUMBER` STRING, `ONE_TIME_ACCOUNT` STRING, `ADDRESS` STRING, `TITLE` STRING, `CREATED_DATE` DATE, `CUST_ACCT_GRP` STRING, `CTRL_DELV_BLOCK` STRING, `DISTRICT` STRING, `LANG` STRING, `VAT_REG_NUM` STRING, `PLANT` STRING, `TAX_TYPE` STRING, `TAX_NUM_TYPE` STRING, `GSTN_ID` STRING, `NAME_REPRESENTATIVE` STRING, `BUSINESS_TYPE` STRING, `INDUSTRY_TYPE` STRING, `GROUP_ID` STRING,`DIVISION` STRING ,`SALES_TYPE` string,`OUTSTANDING_SBU` STRING,`OUTSTANDING_PRODUCT_LINE` STRING,`CUSTOMER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_CUSTOMER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC CREATE TABLE `pro_prod`.`dim_customer_group` (`CUSTOMER_GROUP_ID` STRING, `CUSTOMER_GROUP_NAME` STRING, `CUSTOMER_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_CUSTOMER_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_date` (`DATE_DT` DATE, `DATE_ID` BIGINT, `DAY_ID` BIGINT, `DAY_NAME` STRING, `DAY_OF_MONTH_NUM` BIGINT, `DAY_OF_YR_NUM` BIGINT, `FY_DAY_OF_MONTH` STRING, `FY_HF_YR_OF_YR` STRING, `FY_HY_NAME` STRING, `FY_MONTH_ID` BIGINT, `FY_MONTH_OF_YR` STRING, `FY_MONTH_OF_YR_NUM` BIGINT, `FY_NAME` BIGINT, `FY_QTR_ID` BIGINT, `FY_QTR_NAME` STRING, `FY_QTR_OF_YR` STRING, `FY_QTR_OF_YR_NUM` BIGINT, `FY_WEEK_ID` BIGINT, `FY_WEEK_OF_YR_NUM` BIGINT, `FY_WK_OF_MONTH_NAME` STRING, `MONTH_ID` BIGINT, `MONTH_OF_YR_NAME` STRING, `MONTH_OF_YR_NUM` BIGINT, `QTR_ID` BIGINT, `QTR_OF_YR_NUM` BIGINT, `WEEK_ID` BIGINT, `WEEK_OF_YR_NUM` BIGINT, `WK_NAME` STRING, `WK_SORT` BIGINT, `YR_NAME` BIGINT, `DATE_CREATED_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_DATE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_distribution_channel` (`DISTRIBUTION_CHANNEL` STRING, `DISTRIBUTION_CHANNEL_DESCRIPTION` STRING, `DIST_CHANNEL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_DISTRIBUTION_CHANNEL'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_division` (`DIVISION_ID` STRING, `DIVISION_NAME` STRING, `DIVISION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_DIVISION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_first_time_sales` (`FIRST_CUST_FLAG` BIGINT, `FIRST_CUST_PRD_SALES_FLAG` BIGINT, `FIRST_PRD_SALES_FLAG` BIGINT, `FIRST_TIME_SALES_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_FIRST_TIME_SALES'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_fpr_detail` (`FPR` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_FPR_DETAIL'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_freight_group` (`MAT_FRGHT_GRP` STRING, `DESCRIPTION` STRING, `MAT_FRGROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_FREIGHT_GROUP'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_hysil_customers` (`CUSTOMER_CODE` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_HYSIL_CUSTOMERS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_personnel` (`PER_NUMBER` STRING, `COMP_CODE` STRING, `PER_AREA` STRING, `EMP_GROUP` STRING, `EMP_SUBGROUP` STRING, `ORG_KEY` STRING, `BUS_AREA` STRING, `COST_CENTER` STRING, `ORG_UNIT` STRING, `POSITION` STRING, `JOB` STRING, `PER_NAME` STRING, `CTRL_AREA` STRING, `FUNDS_CTR` STRING, `FUND` STRING, `FUNC_AREA` STRING, `SEGMENT` STRING, `PER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PERSONNEL'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_plant_depot` (`PLANT_ID` STRING,`PLANT_NAME` STRING,`VALUATION_AREA` STRING,`FACTORY_CAL_KEY` STRING,`PLANT_NAME_2` STRING,`POSTAL_CODE` STRING,`PURCHASE_ORG` STRING,`SALES_ORG` STRING,`COUNTRY` STRING,`REGION` STRING,`ADDRESS` STRING,`DISTRIBUTION_CHANNEL` STRING,`DIVISION` STRING,`LANGUAGE` STRING,`PLANT_CATEGORY` STRING,`SALES_DISTRICT` STRING,`BUSINESS_PLACE` STRING,`STORE_TYPE` STRING,`DEP_STORE` STRING,`DEPOT_ID` STRING,`REPORT_PLANT_ID` STRING,`REPORT_PLANT_NAME` STRING,`IS_PLANT` INTEGER,`STATE` STRING,`ZONE` STRING,`DEPOT_FPR` STRING,`PRODUCT_LINE` STRING,`IS_ACTIVE_DEPOT` INT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PLANT_DEPOT'
# MAGIC   
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_vendor` (`VENDOR_ID` STRING,`COUNTRY` STRING,`NAME` STRING,`NAME2` STRING,`NAME3` STRING,`NAME4` STRING,`CITY` STRING,`DISTRICT` STRING,`POSTAL_CODE` STRING,`REGION` STRING,`STREET` STRING,`ADDRESS` STRING,`CREATED_DATE` DATE,`DELETED_STATUS` STRING,`BLOCKED_STATUS` STRING,`CREATED_BY` STRING,`ACCOUNT_GROUP` STRING,`TELEPHONE_1` STRING,`PLANT` STRING,`GST_NUMBER` STRING,`VENDOR_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_VENDOR'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_service` (`ACTIVITY_NUMBER` string,`CREATED_DATE` date,`CREATED_BY` string,`CHANGED_DATE` date,`DELETION_INDICATOR` string,`BASE_UOM` string,`SERVICE_CATEGORY` string,`SERVICE_TYPE` string,`ACTIVITY_DESCRIPTION` string,`VALUATION_CLASS` string,`MATL_GROUP` string,`ACTIVITY_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_SERVICE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_pricing_group` (`PRICE_GROUP_ID` STRING, `PRICE_GROUP_DESCRIPTION` STRING, `CUST_PRICING_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PRICING_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_product` (`MATERIAL_NUMBER` STRING,`CREATED_DATE` DATE,`CHANGED_DATE` DATE,`DELETION_FLAG` STRING,`MATERIAL_TYPE` STRING ,`MATERIAL_GROUP` STRING, `DIVISION` STRING, `MATERIAL_DESCRIPTION` STRING , `UNIT_OF_MEASURE` STRING, `SBU` STRING, `PRODUCT_LINE` STRING, `PRODUCT_GROUP` STRING, `BRAND` STRING, `CHANNEL` STRING, `PRODUCT_MIX` STRING, `PRODUCT_TYPE` STRING, `ASSEMBLY_TYPE` STRING, `SIZE` STRING, `SOCKET_TYPE` STRING, `FITTINGS_TYPE` STRING, `COLOUR_TYPE` STRING,`FG_MATERIAL_GROUP` STRING ,`COLOUR` STRING, `THICKNESS` STRING, `LENGTH` STRING, `CATEGORY` STRING, `SUB_CATEGORY` STRING, `WIDTH` STRING,`DEPARTMENT` STRING ,`SKU_NUMBER` INT,`CLASSIFICATION_GROUP` string ,`RM_GROUP` string,`RM_GROUP2` string,`MATL_TYPE_DESC` STRING,`MATL_GROUP_DESC` STRING,`MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PRODUCT'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_product_group` (`MATERIAL_GROUP_ID` STRING, `MATERIAL_GROUP_DESCRIPTION` STRING, `MATERIAL_GROUP_DESCRIPTION_2` STRING, `MATERIAL_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PRODUCT_GROUP'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_product_line` (`PRODUCT_LINE` STRING, `DESCRIPTION` STRING, `PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PRODUCT_LINE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_product_pricing_group` (`MAT_PRCNG_GRP` STRING, `DESCRIPTION` STRING, `MATL_PRICING_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PRODUCT_PRICING_GROUP'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_route` (`ROUTE` STRING, `DESCRIPTION` STRING, `ROUTE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_ROUTE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_sale_type` (`SALES_TYPE` STRING, `SALES_TYPE_DESC` STRING, `SALES_TYPE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_SALE_TYPE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_sales_group` (`SALES_GROUP` STRING, `DESCRIPTION` STRING, `SALES_GRP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_SALES_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_sales_office` (`SALES_OFFICE` STRING, `DESCRIPTION` STRING, `SALES_OFC_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_SALES_OFFICE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_sales_org` (`SALES_ORG` STRING, `STATS_CURR` STRING, `COMPANY_CODE` STRING, `ADDRESS_ID` STRING, `ADDR_TXT_NAME` STRING, `LTTR_HDR_TXT_NAME` STRING, `FTTR_LINES_TXT` STRING, `GRTNG_TXT_NAME` STRING, `REF_SALES_ORG` STRING, `CUST_ID` STRING, `REB_PROC_ACTV` STRING, `SALES_ORG_CAL` STRING, `PUR_ORG` STRING, `PUR_GRP` STRING, `VNDR_ACC_NO` STRING, `PLANT_ID` STRING, `ORD_TYP` STRING, `PUR_DOC_CAT` STRING, `MV_TYP` STRING, `STRG_LOC` STRING, `TXT_SDS_SNDR` STRING, `TAX_NUM` STRING, `VAT_REG_NUM` STRING, `NUMB_TIM` STRING, `MAX_BLLNG_DOC` STRING, `PRC_PRTCN_PRD` STRING, `PRC_PRTCN_UNT` STRING, `SALES_ORG_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_SALES_ORG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_storage_location` (`PLANT_ID` STRING, `STORAGE_LOCATION` STRING, `DESCRIPTION` STRING, `STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_STORAGE_LOCATION'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_chapter` (`CHAPTER_ID` string,`UOM_EXCISE` string,`CHANGED_ON` date,`CHANGED_BY` string,`CHAPTER_DESCRIPTION` string, `CHAPTER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_CHAPTER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`DIM_INSPECTION_CHARS`(`PLANT_ID` string,`MASTER_INSP_CHAR` string,`VERSION` string,`VALID_FROM` date,`DESCRIPTION` string,`INSP_CHAR_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_INSPECTION_CHARS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`dim_territory` (`SALES_ORG` STRING, `PRODUCT_LINE` STRING, `SALE_TYPE` STRING, `PINCODE` STRING, `DISTRICT` STRING, `SALES_GROUP` STRING, `STATE` STRING, `ZONE` STRING, `COUNTRY` STRING, `GEO_DISTRICT` STRING, `GEO_STATE` STRING, `PINCODE_TXT` STRING, `DISTRICT_TXT` STRING, `SALES_GROUP_TXT` STRING, `STATE_TXT` STRING, `ZONE_TXT` STRING, `COUNTRY_TXT` STRING, `RLS` STRING, `GEO_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_TERRITORY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table `pro_prod`.`dim_defect` (`DEFECT_GROUP` STRING,`DEFECT_CODE` STRING,`DESCRIPTION` STRING,`DEFECT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_DEFECT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_cust_payment_outstanding` (`0_TO_15_DAYS` DECIMAL(38,2), `106_TO_120_DAYS` DECIMAL(38,2), `121_TO_135_DAYS` DECIMAL(38,2), `136_TO_150_DAYS` DECIMAL(38,2), `151_TO_165_DAYS` DECIMAL(38,2), `166_TO_180_DAYS` DECIMAL(38,2), `16_TO_30_DAYS` DECIMAL(38,2), `181_TO_195_DAYS` DECIMAL(38,2), `196_TO_210_DAYS` DECIMAL(38,2), `211_TO_225_DAYS` DECIMAL(38,2), `226_TO_240_DAYS` DECIMAL(38,2), `241_TO_255_DAYS` DECIMAL(38,2), `256_TO_270_DAYS` DECIMAL(38,2), `271_TO_285_DAYS` DECIMAL(38,2), `286_TO_300_DAYS` DECIMAL(38,2), `301_TO_315_DAYS` DECIMAL(38,2), `316_TO_330_DAYS` DECIMAL(38,2), `31_TO_45_DAYS` DECIMAL(38,2), `331_TO_345_DAYS` DECIMAL(38,2), `346_TO_360_DAYS` DECIMAL(38,2), `361_TO_390_DAYS` DECIMAL(38,2), `391_TO_420_DAYS` DECIMAL(38,2), `421_TO_450_DAYS` DECIMAL(38,2), `451_TO_480_DAYS` DECIMAL(38,2), `46_TO_60_DAYS` DECIMAL(38,2), `481_TO_510_DAYS` DECIMAL(38,2), `511_TO_540_DAYS` DECIMAL(38,2), `541_TO_570_DAYS` DECIMAL(38,2), `571_TO_600_DAYS` DECIMAL(38,2), `601_TO_630_DAYS` DECIMAL(38,2), `61_TO_75_DAYS` DECIMAL(38,2), `631_TO_660_DAYS` DECIMAL(38,2), `661_TO_690_DAYS` DECIMAL(38,2), `691_TO_720_DAYS` DECIMAL(38,2), `76_TO_90_DAYS` DECIMAL(38,2), `91_TO_105_DAYS` DECIMAL(38,2), `GRTR_THAN_720_DAYS` DECIMAL(38,2), `GEO_KEY` BIGINT, `PER_KEY` BIGINT, `CUSTOMER_KEY` BIGINT, `SNAPSHOT_DATE_KEY` BIGINT, `SALES_TYPE_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT, `SALES_ORG_KEY` BIGINT, `LAST_EXECUTED_TIME` TIMESTAMP, `LAST_EXECUTED_DATE` DATE)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_CUST_PAYMENT_OUTSTANDING'
# MAGIC )
# MAGIC PARTITIONED BY (LAST_EXECUTED_DATE)

# COMMAND ----------

# MAGIC %sql
# MAGIC create table `pro_prod`.`FACT_QUALITY_CUSTOMER_SATISFACTION_SURVEY` (`SBU` string,`DEALER_NAME` string,`SUB_DEALER_NAME` string,`SURVEY_TAKEN_BY` string,`ZONE` string,`STATE` string,`REMARKS` string,`RATING` integer,`CATEGORY` string,`QUESTION` string,`CUSTOMER_KEY` long,`DATE_KEY` long,`PRODUCT_LINE_KEY` long)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_CUSTOMER_SATISFACTION_SURVEY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_daily_seasonal_plan` (`BILLING_MONTH` STRING, `STC_PLAN` BIGINT, `STC_ACTUAL` DECIMAL(38,6), `TOTAL_SALES_PLAN` BIGINT, `TOTAL_SALES` DECIMAL(38,8), `BALANCE_DISPATCH` DECIMAL(38,6), `PLANT_DAILY_SALE_PLAN` DOUBLE, `DAILY_STO_PLAN` DOUBLE, `GOOD_QTY_SUM` DECIMAL(38,14), `OPENING_STOCK` DECIMAL(38,13), `IS_PLANT` INT, `PRODUCTION_PLAN` BIGINT, `NET_STOCK_CUMM` DOUBLE, `CLOSING_INVENTORY` DOUBLE, `DEPOT_DAILY_SALE_PLAN` DOUBLE, `DEPOT_OPENING_STOCK` DECIMAL(38,14), `DEPOT_NET_STOCK_CUMM` DOUBLE, `DEPOT_CLOSING_INVENTORY` DOUBLE, `QUANTITY_AFTER_CURING` DECIMAL(34,14), `PLANT_DAILY_NET_DISPATCHABLE_STOCK` DOUBLE, `PLANT_NET_DISPATCHABLE_STOCK_CUMM` DOUBLE, `PLANT_CLOSING_DISPATCHABLE_STOCK` DOUBLE, `PLANT_OPENING_INVENTORY` DOUBLE, `PLANT_OPENING_GOOD_INVENTORY` DOUBLE, `DEPOT_OPENING_INVENTORY` DOUBLE, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_DAILY_SEASONAL_PLAN'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_depot_monthly_targets` (`SALE_PLAN` BIGINT, `CLOSING_INVENTORY` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_DEPOT_MONTHLY_TARGETS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_depot_netloss` (`MATL_DOC` STRING, `MATL_DOC_YEAR` STRING, `DOC_ITEM` STRING, `MOVEMENT_TYPE` STRING,`QUANTITY` DECIMAL(13,3), `UNIT_WEIGHTS` DECIMAL(11,6), `TOTAL_UNIT_WEIGHTS` DECIMAL(25,9), `WEIGHTS_MT` DECIMAL(30,14), `DEPOT_NETLOSS_MT` DECIMAL(30,14),`PLANT_NETLOSS_MT` DECIMAL(30,14),`SENT_RECLAMATION_QTY_MT` DECIMAL(30,14),`RECEIVED_RECLAMATION_QTY_MT` DECIMAL(30,14),`MARKET_NETLOSS` DECIMAL(30,14) ,`DATE_KEY` BIGINT,`SUPPLYING_PLANT_KEY` BIGINT ,`PLANT_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_DEPOT_NETLOSS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_plant_netloss`(`MATL_DOC` string,`MATL_DOC_YEAR` string,`DOC_ITEM` string,`MOVEMENT_TYPE` string,`QUANTITY` decimal(13,3),`UNIT_WEIGHTS` decimal(11,6),`TOTAL_UNIT_WEIGHTS` decimal(25,9),`WEIGHTS_MT` decimal(30,14),`PLANT_NETLOSS_MT` decimal(30,14),`MARKET_NETLOSS` decimal(30,14),`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`STORAGE_LOCATION_KEY` BIGINT)USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_PLANT_NETLOSS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_depot_yearly_targets` (`NET_LOSS_TO_SALE` DECIMAL(13,2), `FREIGHT_TARGET` BIGINT, `DATE_KEY` BIGINT, `PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_DEPOT_YEARLY_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_fpr_yearly_kpi_targets` (`FPR` STRING, `KPI` STRING, `TARGET` DECIMAL(13,2), `DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_FPR_YEARLY_KPI_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_global_yearly_kpi_targets` (`KPI` STRING, `TARGET` DECIMAL(13,5), `DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_GLOBAL_YEARLY_KPI_TARGETS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_inventory` (`BLKD_QTY` DECIMAL(13,3),`QLTY_QT` DECIMAL(13,3),`RTRNS_QTY` DECIMAL(13,3),`REST_QTY` DECIMAL(13,3),`UNREST_QTY` DECIMAL(13,3),`TRSN_QTY` DECIMAL(13,3),`TOTAL_MT` DECIMAL(35,14),`RECLAIMABLE_QTY` DECIMAL(30,14),`DESTROYABLE_QTY` DECIMAL(36,14),`IN_TRANSIT_QTY` DECIMAL(30,14),`GOOD_QTY` DECIMAL(30,14),`STOCK_CURING` DECIMAL(30,14),`STOCK_TAKING_DATE` DATE,`PRICE` DECIMAL(11,2),`UNRESTRICTED_VALUE` DECIMAL(25,5),`QUALITY_VALUE` DECIMAL(25,5),`BLOCKED_VALUE` DECIMAL(25,5),`LAST_EXECUTED_TIME` STRING,`PLANT_KEY` LONG,`MATL_KEY` LONG,`SNAPSHOT_DATE_KEY` LONG,`STORAGE_LOCATION_KEY` LONG)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_INVENTORY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_plant_daily_targets` (`PRODUCTION_PLAN` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_PLANT_DAILY_TARGETS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_plant_depot_capacity` (`CAPACITY` BIGINT, `PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_PLANT_DEPOT_CAPACITY'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_plant_monthly_freight_targets` (`DISPATCH_TYPE` STRING, `VALUE` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_PLANT_MONTHLY_FREIGHT_TARGETS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_plant_monthly_targets` (`SALE_PLAN` BIGINT, `CLOSING_INVENTORY` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_PLANT_MONTHLY_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_production` (`PRODUCTION_ORDER` STRING,`MATL_DOC` STRING,`DOC_ITEM` STRING,`MATL_DOC_YEAR` STRING,`QUANTITY` DECIMAL(15,3),`UNIT_WEIGHT` DECIMAL(18,6),`TOTAL_UNIT_WEIGHT` DECIMAL(34,9),`WEIGHTS_MT` DECIMAL(38,13),`STORAGE_LOCATION` STRING,`MATERIAL_KEY` BIGINT,`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_PRODUCTION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_quality_plant_rls` (`USER_MAIL_ID` STRING, `PLANT_DEPOT_ID` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_PLANT_RLS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_PROCUREMENT_RLS` (`USER_MAIL_ID` STRING, `PLANT_DEPOT_ID` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PROCUREMENT_RLS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_FINANCE_PLANT_RLS` (`USER_MAIL_ID` STRING, `PLANT_DEPOT_ID` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_FINANCE_PLANT_RLS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_FINANCE_SBU_RLS` (`USER_MAIL_ID` STRING, `SBU` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_FINANCE_SBU_RLS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_FINANCE_PROD_LINE_RLS` (`USER_MAIL_ID` STRING, `PRODUCT_LINE` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_FINANCE_PROD_LINE_RLS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_FINANCE_OUTSTANDING_RLS` (`USER_MAIL_ID` STRING, `OUTSTANDING_PRODUCT_LINE` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_FINANCE_OUTSTANDING_RLS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_QUALITY_PLANT_REJECTION (`PRODUCTION_ORDER` string,`MATERIAL_DOC` string,`MATERIAL_DOC_YEAR` string,`DOC_ITEM` string,`MOVEMENT_TYPE` string,`QUANTITY` decimal(13,3),`UNIT_OF_ENTRY` string,`UNIT_WEIGHTS` decimal(11,6),`WEIGHTS_MT` decimal(30,14),`USABLE_REJECTION_QTY_MT` decimal(30,14),`NON_USABLE_REJECTION_QTY_MT` decimal(30,14),`MATERIAL_KEY` long,`DATE_KEY` long,`PLANT_KEY` long,`STORAGE_LOCATION_KEY` long)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_PLANT_REJECTION'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_rls` (`USER_MAIL_ID` STRING, `PLANT_DEPOT_ID` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_RLS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_sales_targets` (`SALES_ORG` STRING, `SALES_TARGETS` DECIMAL(13,2), `GEO_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT, `TARGET_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_SALES_TARGETS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_stc_targets` (`STC_PLAN` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `PLANT_KEY` BIGINT, `DEPOT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_STC_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_logistics_sto` (`INVOICE_DATE` DATE, `INVOICE_NO` STRING, `INVOICE_LINE_ID` STRING, `NET_VALUE` DECIMAL(13,2), `CHALLAN_NO` STRING, `IGST_RATE` DECIMAL(26,6), `CGST_RATE` DECIMAL(26,6), `SGST_RATE` DECIMAL(26,6), `REC_QUANTITY` DECIMAL(25,3), `SALES_UNIT_INFORMATION` STRING, `SUPP_QTY_MT` DECIMAL(32,11), `BASE_UNIT_OF_MEASURE_INFORMATION` STRING, `PO_NUMBER` STRING, `PO_ITEM` STRING, `FREIGHT` DECIMAL(38,6), `TRANSPORTER_CODE` STRING, `SUPP_QUANTITY` DECIMAL(13,3), `REC_QUANTITY_MT` DECIMAL(38,6),`TRANS_TYPE` STRING  ,`LAST_EXECUTED_TIME` STRING,`GEO_KEY` BIGINT ,`SUPPLYING_PLANT_KEY` BIGINT, `SUPPLYING_DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `RECEIVING_PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_LOGISTICS_STO'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_pending_orders_snapshot` (`ORDER_ID` STRING, `ORDER_LINE_ID` STRING, `ACTL_QTY_DELVRD` DECIMAL(33,3), `UNIT_PRICE` DECIMAL(34,18), `BALANCE_QUANTITY` DOUBLE, `PENDING_QTY_WT` DOUBLE, `RELEASED_QTY_WT` DOUBLE, `PENDING_SALES_VALUE` DOUBLE, `RELEASED_SALES_VALUE` DOUBLE, `NET_WGT_INFO` DECIMAL(15,3), `WEIGHT_UNIT` STRING, `ORDER_QTY` DECIMAL(15,3), `ACTL_QTY_DELVRD_NT_WGT` DECIMAL(35,3), `OVRL_STATUS` STRING, `LAST_EXECUTED_TIME` STRING, `MATERIAL_KEY` BIGINT, `PLANT_KEY` BIGINT, `CUSTOMER_KEY` BIGINT, `DATE_CREATED_KEY` BIGINT, `MATL_PRICING_GROUP_KEY` BIGINT, `CUSTOMER_GROUP_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT, `CREATED_DATE` DATE, `SALES_ORG_TYPE` STRING, `GEO_KEY` BIGINT, `SALES_ORG_KEY` BIGINT, `INCO1` STRING, `INCO2` STRING, `NET_VALUE` DECIMAL(25,2), `SHIP_TO_CUST_ID` STRING, `REASON_FOR_REJECTION` STRING, `LAST_EXECUTED_DATE` DATE)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PENDING_ORDERS_SNAPSHOT'
# MAGIC )
# MAGIC PARTITIONED BY (LAST_EXECUTED_DATE)
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_pending_orders_snapshot_temp` (`ORDER_ID` STRING, `ORDER_LINE_ID` STRING, `ACTL_QTY_DELVRD` DECIMAL(33,3), `UNIT_PRICE` DECIMAL(34,18), `BALANCE_QUANTITY` DOUBLE, `PENDING_QTY_WT` DOUBLE, `RELEASED_QTY_WT` DOUBLE, `PENDING_SALES_VALUE` DOUBLE, `RELEASED_SALES_VALUE` DOUBLE, `NET_WGT_INFO` DECIMAL(15,3), `WEIGHT_UNIT` STRING, `ORDER_QTY` DECIMAL(15,3), `ACTL_QTY_DELVRD_NT_WGT` DECIMAL(35,3), `OVRL_STATUS` STRING, `LAST_EXECUTED_TIME` STRING, `MATERIAL_KEY` BIGINT, `PLANT_KEY` BIGINT, `CUSTOMER_KEY` BIGINT, `DATE_CREATED_KEY` BIGINT, `MATL_PRICING_GROUP_KEY` BIGINT, `CUSTOMER_GROUP_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT, `CREATED_DATE` DATE, `SALES_ORG_TYPE` STRING, `GEO_KEY` BIGINT, `SALES_ORG_KEY` BIGINT, `INCO1` STRING, `INCO2` STRING, `NET_VALUE` DECIMAL(25,2), `SHIP_TO_CUST_ID` STRING, `REASON_FOR_REJECTION` STRING, `LAST_EXECUTED_DATE` DATE)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PENDING_ORDERS_SNAPSHOT_TEMP'
# MAGIC )
# MAGIC PARTITIONED BY (LAST_EXECUTED_DATE)

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_rls` (`USER_MAIL_ID` STRING, `PRODUCT_LINE` STRING, `SALE_TYPE` STRING, `RLS` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RLS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_SBU_RLS` (`USER_MAIL_ID` STRING,`SBU` STRING, `PRODUCT_TYPE` STRING, `RLS` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_SBU_RLS'
# MAGIC )

# COMMAND ----------



# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_PLANT_REJECTION_RCA_CAPA` (`SBU` string,`DEFECT_TYPE` string,`DEFECT_QTY_NOS` decimal(13,2),`RCA_STATUS` string,`REASON` string,`CAPA_PLAN` string,`CAPA_STATUS` string,`RESPONSIBILITY` string,`REMARKS` string,`DATE_CREATED_KEY` long,`PLANT_KEY` long)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_PLANT_REJECTION_RCA_CAPA'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_sales_invoice` (`INVOICE_ID` STRING, `INVOICE_LINE_ID` STRING, `QUANTITY` DECIMAL(13,3),`QUANTITY_EA` DECIMAL(20,8), `STORAGE_LOC` STRING, `VOLUME_UNIT` STRING, `GROSS_WEIGHT` DECIMAL(34,11), `ITEM_CREDIT_PRICE` DECIMAL(11,2), `NET_VALUE` DECIMAL(15,2), `TAX_AMT` DECIMAL(13,2), `WEIGHT_UNIT` STRING, `DOC_CRCY` STRING, `BILLING_TYPE` STRING, `VEHICLE_NO` STRING, `LR_NO` STRING, `DRIVER_CONT_NO` STRING, `WAYBILL_NO` STRING, `REGION` STRING, `VOLUME` DECIMAL(15,3), `BUSINESS_PLACE` STRING, `COMPANY_CODE` STRING, `EXCISE_DUTY_DATE` DATE, `EXCISE_DUTY_NUM` STRING, `DISTRICT` STRING, `ORDER_TYPE` STRING, `CUST_TYPE` STRING, `PSTLZ` STRING, `INCO1` STRING, `INCO2` STRING, `ASSESSIBLE_VALUE2` DECIMAL(34,2), `SECDRY_FREIGHT` DECIMAL(25,2), `TRADE_DIS` DECIMAL(33,2), `KERALA_DISC` DECIMAL(33,2), `KERALA_DISC_RATE` DECIMAL(26,6), `EXCISE_CONDITIONS` DECIMAL(26,6), `ENTRY_TAX_PERC` DECIMAL(26,6), `CST_PERC` DECIMAL(26,6), `VAT_PERC` DECIMAL(26,6), `ADDL_TAX_PERC` DECIMAL(26,6), `TCS_PERC` DECIMAL(26,6), `ORISSA_ENTRY_TAX_PERC` DECIMAL(26,6), `STATE_SEC_TAX_PERC` DECIMAL(26,6), `BASE_PRICE_DISC` DECIMAL(26,6), `RATE_DIFF` DECIMAL(25,6), `OCEAN_AIR_FREIGHT` DECIMAL(38,7), `PACKING_HIL_EXPORT` DECIMAL(38,7), `FOB_VALUE` DECIMAL(38,7), `ZCMP` DECIMAL(38,7), `TAXABLE_TURNOVER` DECIMAL(38,7), `CGST_PERC` DECIMAL(26,6), `CGST_AMNT` DECIMAL(33,2), `SGST_PERC` DECIMAL(26,6), `SGST_AMNT` DECIMAL(33,2), `IGST_PERC` DECIMAL(26,6), `IGST_AMNT` DECIMAL(33,2), `UGST_PERC` DECIMAL(26,6), `UGST_AMNT` DECIMAL(33,2), `BASE_PRICE_HIL` DECIMAL(33,2), `BASE_PRICE` DECIMAL(25,2), `FREIGHT_HIL` DECIMAL(33,2), `FREIGHT_ZF02` DECIMAL(33,2), `FREIGHT_ZF01` DECIMAL(33,2), `TOTAL_FREIGHT` DECIMAL(33,2), `MULTIPLICATION_FACTOR` DECIMAL(33,2), `INSURANCE` DECIMAL(23,2),`MRP` DECIMAL(23,2),`PF_ADDL_DISC` DECIMAL(25,2),`LOGISTICS_SUPPORT` DECIMAL(25,2),`PF_CD_ON_BILLING` DECIMAL(25,2),`ORC` DECIMAL(23,2),`PF_PRICE_DIFF` DECIMAL(23,2),`ZOD1` DECIMAL(23,2),`ZOD2` DECIMAL(23,2),`WP_ADDL_DISC` DECIMAL(23,2),`WP_PRICE_DIFF` DECIMAL(23,2),`WP_CD_ON_BILLING` DECIMAL(23,2),`ZRPB` DECIMAL(23,2),`ZRPC` DECIMAL(23,2) , `ZBPB_PU` DECIMAL(38,14), `SALES_ORG_TYPE` STRING, `TOTAL_SALES_VALUE` DECIMAL(35,2),`TRANS_TYPE` STRING ,`GEO_KEY` BIGINT,`SHIP_TO_GEO_KEY` BIGINT,`DIVISION_KEY` BIGINT, `PLANT_KEY` BIGINT, `SALES_ORG_KEY` BIGINT, `DIST_CHANNEL_KEY` BIGINT, `SALES_TYPE_KEY` BIGINT, `DATE_CREATED_KEY` BIGINT, `PAYER_CUST_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `PAYER_ADDR_KEY` BIGINT, `SALES_PER_KEY` BIGINT, `BILLING_DATE_KEY` BIGINT, `SOLD_TO_PARTY_KEY` BIGINT, `AGENT_ADDR_KEY` BIGINT, `AGENT_CUST_KEY` BIGINT, `BILLTO_ADDR_KEY` BIGINT, `BILLTO_CUST_KEY` BIGINT, `SOLDTO_ADDR_KEY` BIGINT, `SHIPTO_ADDR_KEY` BIGINT, `SHIPTO_CUST_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT,`TRANSPORTER_KEY` BIGINT ,`FIRST_TIME_SALES_KEY` BIGINT, `LAST_EXECUTED_TIME` TIMESTAMP, `INVOICE_STATUS` STRING)
# MAGIC USING DELTA
# MAGIC OPTIONS (
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SALES_INVOICE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_sales_targets` (`SALES_TARGETS` DECIMAL(34,23), `NSR_TARGETS` DECIMAL(13,2), `QUANTITY_TARGETS` DECIMAL(34,23), `GEO_KEY` BIGINT, `SALES_ORG_KEY` BIGINT, `SALES_TYPE_KEY` BIGINT, `TARGET_DATE_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SALES_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_security_deposit` (`CUSTOMER_KEY` BIGINT, `SECURITY_DEPOSIT` DECIMAL(25,2), `SNAPSHOT_DATE_KEY` BIGINT,`LAST_EXECUTED_TIME` timestamp,`MONTH` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SECURITY_DEPOSIT'
# MAGIC )
# MAGIC PARTITIONED BY (MONTH)

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_sip_sales` (`SERIAL_NO` STRING, `AMOUNT` DECIMAL(13,2), `QUANTITY` DECIMAL(13,2), `RETAILER_ID` STRING, `OUTLET_NAME` STRING, `PRIMARY_MOBILE` STRING, `RETAILER_NAME` STRING, `FIRM_NAME` STRING, `SAP_ID` STRING, `CITY` STRING, `STATE` STRING, `RETAILER_PINCODE` STRING, `CUSTOMER_PINCODE` STRING, `SCHEME` STRING, `GEO_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT, `DATE_KEY` BIGINT, `FIRST_TIME_SALES_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SIP_SALES'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`inventory` (`BLKD_QTY` DECIMAL(13,3), `QLTY_QT` DECIMAL(13,3), `RTRNS_QTY` DECIMAL(13,3), `REST_QTY` DECIMAL(13,3), `UNREST_QTY` DECIMAL(13,3), `TRSN_QTY` DECIMAL(13,3), `TOTAL_MT` DECIMAL(35,14), `RECLAIMABLE_QTY` DECIMAL(30,14), `DESTROYABLE_QTY` DECIMAL(36,14), `IN_TRANSIT_QTY` DECIMAL(30,14), `GOOD_QTY` DECIMAL(30,14), `STOCK_CURING` DECIMAL(30,14), `STOCK_TAKING_DATE` DATE,`PRICE` DECIMAL(11,2),`UNRESTRICTED_VALUE` DECIMAL(25,5),`QUALITY_VALUE` DECIMAL(25,5),`BLOCKED_VALUE` DECIMAL(25,5), `PLANT_KEY` BIGINT, `MATL_KEY` BIGINT, `SNAPSHOT_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/INVENTORY'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`inventory_optimised` (`matl_key` STRING, `plant_key` STRING, `blkd_qty` DECIMAL(13,3), `qlty_qty` DECIMAL(13,3), `rtrns_qty` DECIMAL(13,3), `rest_qty` DECIMAL(13,3), `unrest_qty` DECIMAL(13,3), `trsn_qty` DECIMAL(30,14), `storage_loc` STRING, `TOTAL_MT` DECIMAL(35,14), `in_transit_qty` DECIMAL(30,14), `reclaimable_qty` DECIMAL(30,14), `good_qty` DECIMAL(30,14), `stock_curing` DECIMAL(30,14), `destroyable_qty` DECIMAL(36,14), `stock_taking_date` DATE, `last_executed_time` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/INVENTORY_OPTIMIZED'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_quality_sample_tracker` (`REF_NO` string,`CONTROL_NO` long,`SAMPLE_NAME` string,`FINAL_REMARKS` string,`STATUS` STRING,`TEST_RESULT` string,`PRODUCT_NAME` string,`DATE_CREATED_KEY` BIGINT,`PLANT_KEY` BIGINT,`VENDOR_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_SAMPLE_TRACKER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`fact_cms` (`COMPLAINT_TRACKING_NO` STRING,`SECONDARY_CUSTOMER` STRING,`CUSTOMER_CATEGORY` STRING,`COMPLAINT_CODE` STRING,`CUSTOMER_CODE` string,`CUSTOMER_NAME` string,`INVOICE_NO` STRING,`DOC_STATUS` STRING,`LOCATION_CODE` STRING,`CITY_CODE` STRING,`STATE_DESC` STRING,`SALES_PERSON_CODE` STRING,`SALES_PERSON_ROLE` STRING,`BUSINESS_UNIT` STRING,`PRODUCT_TYPE` STRING,`REGISTERED_DATE` DATE,`INVESTIGATION_NO` INTEGER,`ATTENDED_DATE` DATE,`DATE_OF_VISIT` DATE,`INVESTIGATION_DONE_BY` STRING,`DELAY_DAYS` INTEGER,`DELAY_REASON` STRING,`SUPPLIED_QTY` DECIMAL(23,2),`BREAKAGE_DEFECT_QTY` DECIMAL(23,2),`NET_LOSS_QTY` DECIMAL(23,2),`INVESTIGATION_STATUS` STRING,`COMPLAINT_STATUS` STRING,`COMPENSATION_STATUS` STRING,`COMPENSATION_NO` INTEGER,`COMPENSATION_APPROVED_DATE` DATE,`COMPENSATION_VALUE` DECIMAL(13,2),`REMARKS` STRING,`CANCEL_BY` STRING,`CANCEL_DATE` DATE,`REJECTED_REMARKS` STRING,`COMPENSATION_NAME` STRING,`REGISTERED_BY` STRING,`REGISTERED_EMPLOYEE_ROLE` STRING,`CI_VISIT_DATE` DATE,`INVESTIGATED_DATE` DATE,`REJECTED_DATE` DATE,`NO_OF_DAYS` DOUBLE,`NO_OF_DAYS_TO_COMPENSATION` DOUBLE,`NO_OF_DAYS_FOR_REJECTION` DOUBLE,`NO_OF_DAYS_TO_CLOSE_COMPLAINT` DOUBLE,`COMPLAINT_CATEGORY` STRING,`DEFECT_TYPE` STRING,`ZONE_NAME` STRING,`RLS` STRING,`INVESTIGATION_DONE_BY_ROLE` STRING,`REGISTERED_BY_NAME` STRING,`SALES_PERSON_NAME` STRING,`INVESTIGATION_DONE_BY_NAME` STRING,`SBU_RLS` STRING,`PARTY_TYPE_DESC` string,`COMPLAINT_TYPE_DESC` string,`PARTY_CODE` string,`PARTY_NAME` string,`PARTY_ADDRESS` string,`PARTY_NUMBER` string,`COMPLAINT_REGISTERED_DATE_KEY` BIGINT,`ATTENDED_DATE_KEY` BIGINT,`VISIT_DATE_KEY` BIGINT,`CUSTOMER_KEY` BIGINT,`INVESTIGATION_PER_KEY` BIGINT,`COMPENSATION_DATE_KEY` BIGINT,`REGISTERED_PER_KEY` BIGINT,`CI_VISIT_DATE_KEY` BIGINT,`INVESTIGATED_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`SALES_REPRESENTATIVE_KEY` BIGINT,`CUSTOMER_GROUP_KEY` BIGINT,`FINAL_DATE_KEY` BIGINT,`REJECTED_DATE_KEY` BIGINT
# MAGIC )
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_CMS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_FIELD_COMPETITOR_SURVEY` (`SBU` STRING,`ZONE` STRING,`CONFORMANCE` STRING,`PARAMETER` STRING,`PARAMETER_DESCRIPTION` STRING,`PRODUCT_LINE` STRING,`REMARKS` STRING,`COMPANY` STRING,`RATING` INT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_FIELD_COMPETITOR_SURVEY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_PRODUCT_BENCHMARKING` (`SBU` STRING,`MATERIAL_DESCRIPTION` STRING,`CATEGORY` STRING,`PARAMETER` STRING,`UOM` STRING,`MINIMUM_SPECIFICATION` STRING,`MAXIMUM_SPECIFICATION` STRING,`REMARKS` STRING,`COMPANY` STRING,`RATING` INT,`DATE_KEY` BIGINT,`MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_PRODUCT_BENCHMARKING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_BIS` (`PRODUCT_LINE` STRING,`TYPE_OF_CERTIFICATION` STRING,`SCOPE_OF_CERTIFICATION` STRING,`CERTIFICATION_NO` STRING,`SCOPE_OF_STANDARD` STRING,`FREQUENCY_OF_RENEWAL` STRING, `RENEWAL_DATE` DATE,`EXPIRY_DATE` DATE,`APPLICATION_DATE_FOR_NEXT_RENEWAL` DATE,`PLANT_KEY` BIGINT,`RENEWAL_DATE_KEY` BIGINT,`EXPIRY_DATE_KEY` BIGINT,`DATE_FOR_RENEWAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_BIS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_COPQ` (`SBU` STRING,`COPQ_TYPE` STRING,`DESCRIPTION` STRING, `S_NO` STRING,`COST_TO_BE_CONSIDERED` STRING,`UOM` STRING,`COST` DECIMAL(10,2),`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_COPQ'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_COPQ` (`SBU` STRING,`COPQ_TYPE` STRING,`DESCRIPTION` STRING, `S_NO` STRING,`COST_TO_BE_CONSIDERED` STRING,`UOM` STRING,`COST` DECIMAL(10,2),`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (IMP
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_COPQ'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_LSS` (`FINANCIAL_YEAR` LONG,`SBU` STRING,`LOCATION` STRING,`SMART_LSS_PROJECT_TITLE` STRING,`PROJECT_START_DATE` STRING,`PROJECT_CLOSURE_DATE` STRING,`TOOLS_USED_FOR_PROBLEM_SOLVING` STRING,`IMPACT_ON_BUSINESS_LEVER` STRING,`PROJECT_THEME` STRING,`ANNUALIZED_SAVINGS` DECIMAL(13,2),`ACCRUED_SAVINGS` DECIMAL(13,2),`PROJECT_STATUS` STRING,`PROJECT_LEAD` STRING,`NO_OF_TEAM_MEMBERS` BIGINT,`STATUS_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_LSS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_LSS_REWARDS_RECOGNITION` (`BUSINESS_UNIT` STRING,`LOCATION` STRING,`YELLOW_BELT_TRAINED_EMPLOYEES` INTEGER,`GREEN_BELT_TRAINED_EMPLOYEES` INTEGER,`BLACK_BELT_TRAINED_EMPLOYEES` INTEGER,`PARTICIPANTS_WHO_INITIATED_LSS_PROJECTS` INTEGER,`PARTICIPANTS_WHO_COMPLETED_LSS_PROJECTS` INTEGER,`REWARDS_RECOGNITION_EVENTS_CONDUCTED` INTEGER,`YELLOW_BELT_CERTIFICATIONS_AWARDED` INTEGER,`GREEN_BELT_CERTIFICATIONS_AWARDED` INTEGER,`BLACK_BELT_CERTIFICATIONS_AWARDED` INTEGER,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_LSS_REWARDS_RECOGNITION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_LSS_CAPABILITY_BUILDING` (`FINANCIAL_YEAR` STRING,`BUSINESS_UNIT` STRING,`LOCATION` STRING,`TRAINER_NAME` STRING,`TRAINING_MEDIUM` STRING,`TRAINING_TOPIC` STRING,`TRAINING_DURATION` INTEGER,`TARGETED_PARTICIPANTS` INTEGER,`ATTENDED_PARTICIPANTS` INTEGER,`CLEARED_ASSESSMENT_PARTICIPANTS` INTEGER,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_LSS_CAPABILITY_BUILDING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_DEPOT_REJECTION` (`ACK_NUM` string,`FINANCIAL_YEAR` string,`GOOD_STOCK` decimal(13,3),`QUANTITY_MT` decimal(30,14),`DEFECTIVE_STOCK` decimal(13,3),`REJECTION_MT` decimal(30,14),`REJECTION` decimal(31,18),`REJECTION_PERC` decimal(35,18),`VEHICLE_NUM` string,`TRANSPORTER_DETAILS` STRING,`SUPPLYING_PLANT_KEY` BIGINT,`RECEIVING_PLANT_KEY` BIGINT,`DATE_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_DEPOT_REJECTION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_PLANT_TRIAL` (`SBU` STRING,`PRODUCT_TYPE` STRING,`TRIAL_DESCRIPTION` STRING,`OBJECTIVE` STRING,`REMARKS` STRING,`STATUS` STRING,`MARKET_FEEDBACK_RECEIVED` STRING,`MARKET_FEEDBACK` STRING,`MANAGEMENT_DECISION` STRING,`PRODUCT_LINE_KEY` LONG,`PLANT_KEY` LONG,`DATE_KEY` LONG)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_PLANT_TRIAL'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_FG_REJECTION_PF` (`WEIGHT_PER_PC` DECIMAL(13,2),`QUANTITY_EA` DECIMAL(13,2),`QUANTITY_KG` DECIMAL(13,2),`REJECTION_JUSTIFICATION` STRING,`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT,`MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_FG_REJECTION_PF'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_INPROCESS_REJECTION` (`WORK_CENTER` STRING,`SHIFT_A_DEFECT_QTY_EA` BIGINT,`SHIFT_B_DEFECT_QTY_EA` BIGINT,`SHIFT_C_DEFECT_QTY_EA` BIGINT,`SHIFT_A_DEFECT_QTY_MT` DECIMAL(38,8),`SHIFT_B_DEFECT_QTY_MT` DECIMAL(38,8),`SHIFT_C_DEFECT_QTY_MT` DECIMAL(38,8),`SHIFT_A_PRODUCTION_QTY_MT` DECIMAL(38,11),`SHIFT_B_PRODUCTION_QTY_MT` DECIMAL(38,11),`SHIFT_C_PRODUCTION_QTY_MT` DECIMAL(38,11),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`DEFECT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_INPROCESS_REJECTION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_PROCESS_AUDIT`(`SBU` STRING,`AUDIT_TYPE` STRING,`AUDIT_DONE_BY` STRING,`FACILITY_NAME` STRING,`TYPE_OF_FACILITY` STRING,`OBJECTIVE_OF_VISIT` STRING,`AREAS_OBSERVED` STRING,`FUNCTION` STRING,`NO_OF_OBSERVATIONS` INTEGER,`NO_OF_OBSERVATIONS_CLOSED` INTEGER,`NO_OF_CRITICAL_OBSERVATIONS` INTEGER,`NO_OF_CRITICAL_OBSERVATIONS_CLOSED` INTEGER,`NO_OF_REPETITIVE_OBSERVATIONS_AFTER_CLOSURE` INTEGER,`REMARKS` STRING,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_PROCESS_AUDIT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_MFG_COMPLAINTS`(`SBU` STRING,`TRACKING_NO` STRING,`COMPLIANT_TYPE` STRING,`MATERIAL_CATEGORY` STRING,`MATERIAL_SUB_CATEGORY` STRING,`DEFECT_TYPE` STRING,`QUANTITY_EA` DECIMAL(13,2),`QUANTITY_MT` DECIMAL(13,2),`BATCH_NUMBER` STRING,`COMPLAINT_STATUS` STRING,`ACTION_IDENTIFIED_FROM_INVESTIGATION` STRING,`ACTION_STATUS` STRING,`REGISTERED_DATE_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT,`SUPPLYING_PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_MFG_COMPLAINTS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_TRIAL_MATERIAL_DISPATCH`(`TRIAL_DATE` DATE,`SBU` STRING,`TRIAL_MATERIAL_DETAILS` STRING,`DEALER_NAME` STRING,`SUB_DEALER_NAME` STRING,`MOBILE_NO` STRING,`AREA` STRING,`AREA_1` STRING,`STATE` STRING,`INVOICE_NO` STRING,`TRUCK_NO` STRING,`SIZE` STRING,`QTY_SUPPLIED` DECIMAL(13,2),`BATCH_NO` STRING,`CUSTOMER_FEEDBACK_FOR_SPECIFIC_CHARACTERISTIC` STRING,`DEFECT_TYPE` STRING,`DEFECT_QTY` DECIMAL(13,2),`TRIAL_DATE_KEY` BIGINT,`DISPATCH_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT,`MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_TRIAL_MATERIAL_DISPATCH'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_PLANT_QUALITY_RATING`(`SBU` STRING,`GROUP_NAME` STRING,`QUALITY_PARAMETER` STRING,`RATING_ACTUAL_VALUE` DECIMAL(13,2),`RATING_TARGET_VALUE` INTEGER,`ACTUAL_VALUE` DECIMAL(13,2),`VALUE_TARGET` string,`DATE_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PLANT_QUALITY_RATING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC CREATE TABLE `pro_prod`.`FACT_VENDOR_QUALITY_RATING` ( `INSPECTION_LOT` STRING, `QUALITY_SCORE` DECIMAL(3,0),`REMARKS` STRING ,`POSTING_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`VENDOR_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`MEAN_VALUE` STRING )
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_VENDOR_QUALITY_RATING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC CREATE TABLE `pro_prod`.`FACT_QUALITY_NCP_SORTING` (`NCP_QUANTITY` DECIMAL(13,2),`SORTING_GRADING_QUANTITY` DECIMAL(13,2),`DATE_CREATED_KEY` LONG,`PLANT_KEY` LONG,`PRODUCT_LINE_KEY` LONG)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_NCP_SORTING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_QUALITY_LOADING_BREAKAGES (`PRODUCTION_ORDER` STRING,`INSPECTION_LOT` STRING,`BREAKAGE_QTY_EA` INTEGER,`BREAKAGE_QTY_MT` DECIMAL(29,8),`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`DATE_CREATED_KEY` BIGINT,`DEFECT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_QUALITY_LOADING_BREAKAGES'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_INSPECTION_CHARS_RESULT(`INSPECTION_LOT` STRING,`PRODUCTION_ORDER` STRING,`UNIT_OF_MEASUREMENT` STRING,`UPPER_LIMIT` DECIMAL(13,3),`LOWER_LIMIT` DECIMAL(13,3),`TARGET_VALUE` DECIMAL(13,3),`ACTUAL_VALUE` DECIMAL(13,3),`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`CREATED_DATE_KEY` BIGINT,`INSP_CHAR_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_INSPECTION_CHARS_RESULT'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PRODUCTION_ORDER_CONFIRMATIONS(   
# MAGIC `PRODUCTION_ORDER` STRING,`CREATED_DATE` DATE,`STANDARD_RM_WT` DECIMAL(28,3),`STANDARD_RM_WT_SPLIT` DECIMAL(38,4),`PLANNED_QTY_EA` DECIMAL(13,3),`PLANNED_QTY_EA_SPLIT` DECIMAL(34,3),`ORDER_TYPE` STRING,`STATUS` STRING,`ACTUAL_RM_WT` DECIMAL(28,3),`PRD_QTY_EA` DECIMAL(23,3),`PROCESS_REJECTION` DECIMAL(28,3),`RUNNER_WASTAGE` DECIMAL(28,3),`NON_USABLE_WASTAGE` DECIMAL(28,3),`GRINDING_CONSUMPTION` DECIMAL(28,3),`FINAL_PRD_QTY` DECIMAL(23,3),`FINAL_PRD_QTY_SPLIT` DECIMAL(38,3),`MACHINE_DESCRIPTION` STRING,`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`CREATED_DATE_KEY` BIGINT,`POSTING_DATE_KEY` BIGINT,`FLAG` INTEGER
# MAGIC )
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PRODUCTION_ORDER_CONFIRMATIONS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_NON_MOVING_MATERIALS(`BASE_UOM` string,`CURRENCY` string,`QUANTITY` decimal(15,3),`WEIGHTS_MT` decimal(32,14),`VALUE` decimal(38,6),`LAST_RECEIPT_DATE` date,`LAST_GOODS_ISSUE_DATE` date,`LAST_CONSUMPTION_DATE` date,`LAST_GOODS_MOVEMENT_DATE` date,`SNAPSHOT_DATE_KEY` long,`PLANT_KEY` long,`MATERIAL_KEY` long,`LAST_RECEIPT_DATE_KEY` long,`LAST_GOODS_ISSUE_DATE_KEY` long,`LAST_CONSUMPTION_DATE_KEY` long,`LAST_GOODS_MOVEMENT_DATE_KEY` long,`STORAGE_LOCATION_KEY` long)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_NON_MOVING_MATERIALS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_VISIT_TRACKER(`COMPLAINT_TRACKING_NO` string,`REGISTERED_DATE` date,`CUSTOMER_CODE` string,`CUSTOMER_NAME` string,`PRODUCT_TYPE` string,`CUSTOMER_CATEGORY` string,`STATE_DESC` string,`SUPPLIED_QTY` decimal(33,2),`BREAKAGE_DEFECT_QTY` decimal(33,2),`NET_LOSS_QTY` decimal(33,2),`ZONE_NAME` string,`RLS` string,`SECONDARY_CUSTOMER` string,`BUSINESS_UNIT` string,`COMPLAINT_STATUS` string,`NO_OF_DAYS` double,`ATTENDED_DATE_KEY` long,`CUSTOMER_KEY` long,`COMPLAINT_TYPE_DESC` string,`PARTY_CODE` string,`PARTY_NAME` string)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_VISIT_TRACKER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_SCRAP_SALES(`SCRAP_QUANTITY` DECIMAL(13,3),`SCRAP_UNIT` STRING,`SCRAP_SBU` STRING,`NET_VALUE` DECIMAL(15,2),`INVOICE_NO` STRING,`BILLING_DATE_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT,`PAYER_CUSTOMER_KEY` BIGINT,`SOLD_TO_PARTY_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SCRAP_SALES'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_MASTERS_LOG(`MATERIALS_CREATED_COUNT` BIGINT,`MATERIALS_CHANGED_COUNT` BIGINT,`CUSTOMERS_CREATED_COUNT` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_MASTERS_LOG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PLANT_LEVEL_MATERIALS(`ACTIVE` BIGINT,`INACTIVE` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PLANT_LEVEL_MATERIALS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_RM_CONSUMPTION(`PRODUCTION_ORDER` string,`AMOUNT` DECIMAL(23,2),`WITHDRAW_QTY` DECIMAL(38,9),`REQUIREMENT_QTY` DECIMAL(38,9),`PRICE_CONTROL` STRING,`MOVING_AVG_PRICE` DECIMAL(15,6),`WORK_CENTER` STRING,`PRODUCTION_QTY` decimal(38,13) ,`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RM_CONSUMPTION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.DIM_PRODUCTION(`PRODUCTION_ORDER` STRING,`CREATED_DATE` DATE,`PLANT_ID` STRING,`PLANT_NAME` STRING,`FY_MONTH_OF_YR` STRING,`FY_MONTH_ID` LONG)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PRODUCTION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PRODUCTION_DETAIL(`TARGET_QUANTITY` DECIMAL(13,3),`ORDER_KEY` BIGINT,`DATE_CREATED_KEY` BIGINT,`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PRODUCTION_DETAIL'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PRODUCTION_WORKCENTER(`MATL_DOC` STRING,`DOC_ITEM` STRING,`STORAGE_LOC` STRING,`QTY_KEY` DECIMAL(13,3),`UNIT_WEIGHTS` DECIMAL(18,6),`TOTAL_UNIT_WEIGHTS` DECIMAL(32,9),`WEIGHTS_MT` DECIMAL(37,14),`WORKCENTER` STRING,`MATERIAL_KEY` BIGINT,`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`ORDER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PRODUCTION_WORKCENTER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PR (`PURCHASE_REQUISTION` STRING,`ITEM_OF_REQUISTION` STRING,`SHORT_TEXT` STRING,`QUANTITY_REQUESTED` DECIMAL(13,3),`UOM` STRING,`PURCHASE_ORDER` STRING,`QUANTITY_ORDERED` DECIMAL(13,3),`REQUISITIONER` STRING,`RELEASE_INDICATOR` STRING,`VALUATION_PRICE` DECIMAL(11,2),`DOCUMENT_TYPE` STRING,`DELETION_INDICATOR` STRING,`PROCESSING_STATUS` STRING,`CREATION_INDICATOR` STRING,`RELEASE_STRATEGY` STRING,`MPN_MATERIAL` STRING,`STORAGE_LOCATION` STRING,`REQUEST_TRACKING_NO` STRING,`MATL_GRP` STRING,`SHORTAGE_QUANTITY` DECIMAL(13,3),`DELIVERY_DATE_CAEGORY` STRING,`GR_PROCESSING_TIME` DECIMAL(3,0),`PRICE_UNIT` DECIMAL(5,0),`ITEM_CATEGORY` STRING,`ACCT_ASSSIGNMENT_CATEGORY` STRING,`CONSUMPTION` STRING,`DISTRIBUTION_INDICATOR` STRING,`PARTIAL_INVOCIE` STRING,`GOODS_RECEIPT` STRING,`GR_NON_VALUATED` STRING,`INVOICE_RECEIPT` STRING,`OUTLINE_AGREEMENT` STRING,`PRINCIPAL_AGREEMENT_ITEM` STRING,`PURCHASE_INFO_RECORD` STRING,`MRP_CONTROLLER` STRING,`PURCHASE_ORDER_ITEM` STRING,`ENTRY_SHEET` STRING,`VALUATION_TYPE` STRING,`CLOSED` STRING,`RESERVATION` STRING,`SPECIAL_STOCK` STRING,`SETTLEMENT_RES_NO` STRING,`ITEM_SETTLEMENT_RESER` STRING,`FIXED_INDICATOR` STRING,`ORDER_UNIT` STRING,`REVISION_LEVEL` STRING,`RELEASE_GROUP` STRING,`PROMOTION` STRING,`BATCH` STRING,`COMMITMENT_ITEM` STRING,`FUNDS_CENTER` STRING,`PR_FUND` STRING,`ORIGIN_OF_CONFIGURATION` STRING,`CROSS_PLANT_CM` STRING,`COMMITTED_QUANTITY` DECIMAL(13,3),`MATERIAL_CATEGORY` STRING,`SPECIAL_STOCK_VALUATION` STRING,`TOTAL_VALUE` DECIMAL(15,2),`CURRENCY` STRING,`VENDOR_MATERIAL_NUMBER` STRING,`OVERALL_RELEASE_OF_REQUISTIONS` STRING,`MFR_PART_PROFILE` STRING,`LANGUAGE_KEY` STRING,`MANUFACTURER_PART_NO` STRING,`MANUFACTURER` STRING,`EXTERNAL_MANUFACTURER` STRING,`FRAMEWORK_ORDER` STRING,`FRAMEWORK_ORDER_ITEM` STRING,`PLANNED_DELIVERY_TIME` DECIMAL(3,0),`ISSUING_STORAGE_LOCATION` STRING,`REQUIREMENT_URGENCY` STRING,`REQUIREMENT_PRIORITY` STRING,`MIN_REM_SHELF_LIFE` DECIMAL(4,0),`PERIOD_IND_SLED` STRING,`CENTRAL_CONTRACT` STRING,`CENTRAL_CONTRACT_ITEM` STRING,`BUDGET_PERIOD` STRING,`US_GOVERNMENT_FIELDS` STRING,`RESPONSIBLE_ORGANIZATIONAL_UNIT` STRING,`PROCUREMENT_PROFILE` STRING,`IUID_RELEVANT` STRING,`STOCK_SEGMENT` STRING,`REQUIREMENT_SEGMENT` STRING,`PURCHASE_REQUISTION_PROCESSING_STATE` STRING,`BLOCKING_INDICATOR` STRING,`BLOCKING_TEXT` STRING,`CHANGED_ON` DATE,`RELEASE_DATE` DATE,`DELIVERY_DATE` DATE,`PURCHASE_ORDER_DATE` DATE,`COMMITTED_DATE` DATE,`PLANT_KEY` BIGINT,`REQUISTION_DATE_KEY` BIGINT,`CHANGED_ON_KEY` BIGINT,`RELEASE_DATE_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`CREATED_BY_KEY` BIGINT,`SUPPLYING_PLANT_KEY` BIGINT,`DELIVERY_DATE_KEY` BIGINT,`DESIRED_VENDOR_KEY` BIGINT,`FIXED_VENDOR_KEY` BIGINT,`PURCHASE_ORDER_DATE_KEY` BIGINT,`COMMITTED_DATE_KEY` BIGINT,`CUSTOMER_KEY` BIGINT,`VENDOR_KEY` BIGINT,`SC_VENDOR_KEY` BIGINT,`PROCURING_PLANT_KEY` BIGINT,`PURCHASE_ORG_KEY` BIGINT,`PURCHASE_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PR'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PO (`PURCHASE_DOCUMENT` string,`ITEM` string,`PO_TYPE` string,`DELIVERY_COMPLETION_FLAG` string,`UNDER_TOLERANCE` decimal(3,1),`OVER_TOLERANCE` decimal(3,1),`ORDER_QUANTITY` decimal(13,3),`ORDER_UNIT` string,`NET_PRICE` decimal(11,2),`NET_ORDER_VALUE` decimal(13,2),`CURRENCY` string,`DOWN_PAYMENT_TYPE` string,`DOWN_PAYMENT_PERC` decimal(5,2),`DOWN_PAYMENT_AMOUNT` decimal(11,2),`DOWN_PAYMENT_DUE_DATE` date,`COLLECTIVE_NUMBER` string,`DELETION_INDICATOR` string,`RELEASE_INDICATOR` string,`RELEASE_GROUP` string,`RELEASE_STATUS` string,`RELEASE_STRATEGY` string,`PO_DOC_CATEGORY` string,`ITEM_CATEGORY` string,`ACCT_ASSIGNMENT_CATEGORY` string,`REQ_TRACKING_NUMBER` string,`STORAGE_LOCATION` string,`PRICE_UNIT` decimal(5,0),`OUTLINE_AGREEMENT` string,`PRINCIPAL_AGREEMENT_ITEM` string,`TARGET_VAL_HEADER` decimal(15,2),`TARGET_QUANTITY` decimal(13,3),`VALIDITY_PERIOD_START` date,`VALIDITY_PERIOD_END` date,`QUOTATION_DEADLINE` date,`RFQ_STATUS` string,`CONTROL_INDICATOR` string,`PACKAGE_NUMBER` string,`ISSUING_STORAGE_LOC` string,`PURCHASE_ORDER_UNIT` string,`TAX_CODE` string,`TAX_JURISDICTION` string,`INCOMPLETE` string,`STOCK_SEGMENT` string,`REQUIREMENT_SEGMENT` string,`CONFIGURABLE_ITEM_NUMBER` string,`EXTERNAL_SORT_NUMBER` string,`EXTERNAL_HIERARCHY_CATEGORY` string,`REQUIREMENT_URGENCY` string,`REQUIREMENT_PRIORITY` string,`ACTUAL_DELIVERY_DATE` date ,`EXPECTED_DELIVERY_DATE` date,`PR_RELEASE_DATE` date,`DELIVERED_QUANTITY` decimal(24,3),`DELIVERED_VALUE` decimal(24,2),`STILL_TO_BE_DELIVERED_QTY` decimal(25,3),`STILL_TO_BE_DELIVERED_VALUE` decimal(25,2),`INVOICED_QUANTITY` decimal(24,3),`INVOICED_VALUE` decimal(24,2),`STILL_TO_BE_INVOICED_QTY` decimal(25,3),`STILL_TO_BE_INVOICED_VALUE` decimal(25,2),`SERVICE_HEADER_QUANTITY` decimal(23,3),`PO_STATUS` STRING,`DOWN_PAYMENT_DUE_DATE_KEY` BIGINT,`VALIDITY_PERIOD_START_DATE_KEY` BIGINT,`VALIDITY_PERIOD_END_DATE_KEY` BIGINT,`QUOTATION_DEADLINE_DATE_KEY` BIGINT,`ACTUAL_DELIVERY_DATE_KEY` BIGINT,`EXPECTED_DELIVERY_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`VENDOR_KEY` BIGINT,`DOCUMENT_DATE_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`PURCHASE_GROUP_KEY` bigint,`PURCHASE_ORG_KEY` bigint)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PO'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_SHORT_CLOSED_PO(`PURCHASE_ORDER` STRING,`ITEM` STRING,`PO_QUANTITY` DECIMAL(13,3),`STATUS` STRING,`UNIT` STRING,`QUANTITY` DECIMAL(24,3),`UNDER_TOLERANCE` DECIMAL(3,1),`OVER_TOLERANCE` DECIMAL(3,1),`PO_TYPE` STRING,`BUYER` STRING,`MATERIAL_KEY` BIGINT,`PO_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SHORT_CLOSED_PO'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_MATERIAL_VALUATION (`PRICE_CONTROL` string,`MOVING_PRICE` decimal(11,2),`STANDARD_PRICE` decimal(11,2),`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_MATERIAL_VALUATION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_SERVICE_MASTER_LOG (`CHANGES_COUNT` long,`UNBLOCK_CHANGES` long,`BLOCK_CHANGES` long,`DATE_KEY` long)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SERVICE_MASTER_LOG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_BUYER_WISE_SAVINGS (`PROPOSAL_NO` string,`SHORT_DESCRIPTION` string,`PURCHASER_GROUP` string,`PURCHASER` string,`PO_NUMBER` string,`PO_TYPE` STRING,`BENCHMARK` string,`ACTUAL_INR` decimal(13,2),`FINAL_INR` decimal(13,2),`SAVINGS_INR` decimal(13,2),`PROPOSAL_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_BUYER_WISE_SAVINGS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_FREIGHT_BUDGET_INR_MT (`FREIGHT_CLASSIFICATION` string,`FREIGHT_BUDGET_INR` decimal(13,2),`PRODUCT_LINE_KEY` long,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_FREIGHT_BUDGET_INR_MT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_RESIN_PRICE
# MAGIC (`PRICE_TYPE` string,`PRICE_VALUE` decimal(13,2),`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RESIN_PRICE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PO_HEADER_CHANGES(`PURCHASE_DOC_NUMBER` STRING ,`ITEM` string,`COLUMN_NAME` string,`VALUE_NEW` string,`VALUE_OLD` string,`DOC_TYPE` string,`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PO_HEADER_CHANGES'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_SALES_ORG_CUSTOMERS(`SALES_ORG` STRING,`CUSTOMER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SALES_ORG_CUSTOMERS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_CUSTOMER_MASTER_LOG (`CHANGES_COUNT` BIGINT,`CHANGED_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_CUSTOMER_MASTER_LOG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table pro_prod.FACT_MATERIAL_MASTER_LOG

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_MATERIAL_MASTER_LOG (`CHANGES_COUNT` BIGINT,`UNBLOCK_CHANGES` BIGINT,`BLOCK_CHANGES` BIGINT,`INACTIVE_CHANGES` BIGINT,`ACTIVE_CHANGES` BIGINT,`CHANGED_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_MATERIAL_MASTER_LOG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_RM_PROCUREMENT (`PURCHASE_DOC` string,`ITEM` string,`DOC_NUMBER` string,`QUANTITY` decimal(13,3),`UOM` string,`WEIGHTS_MT` decimal(25,9),`AMOUNT` decimal(13,2),`BUDGET_AMOUNT` decimal(10,2),`VENDOR_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RM_PROCUREMENT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_RM_PROCUREMENT_BUDGETS (`SBU` STRING,`BUDGET_AMOUNT` DECIMAL(10,2),`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RM_PROCUREMENT_BUDGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_IMPORT_MIS(`PURCHASE_DOC` string,`ITEM` string,`SHIPPING_LINE` string,`QUANTITY` decimal(18,8),`UOM` string,`NET_PRICE` decimal(11,2),`CURRENCY` string,`INVOICE_DATE` date,`BILL_OF_ENTRY_DATE` date,`BILL_OF_ENTRY_NO` string,`BL_NO` string,`ACTUAL_PLANT_DELIVERY_DATE` date,`BOE_EXCHANGE_RATE` decimal(9,5),`BASIC_CUSTOM_DUTY` decimal(21,2),`ANTI_DUMPING_DUTY` decimal(21,2),`SOCIAL_WELFARE` decimal(21,2),`DELIVERY_ORDER_FEES` decimal(21,2),`CONCORE_CHARGES` decimal(22,2),`CLRG_AGENT_SERVICES` decimal(21,2),`INLAND_FREIGHT_VALUE` decimal(21,2),`CLEARING_CHARGES` decimal(21,2),`OCEAN_FREIGHT` decimal(21,2),`INLAND_HAULAGE` decimal(21,2),`SUPPLIER_ID_KEY` BIGINT,`CREATED_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`INVOICE_DATE_KEY` BIGINT,`BILL_OF_ENTRY_DATE_KEY` BIGINT,`DELIVERY_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_IMPORT_MIS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_RM_NEW_VENDOR_DEVELOPMENT(`MATERIAL_DESCRIPTION` STRING,`VENDOR_NAME` STRING,`ADDRESS` STRING,`SAMPLE_QTY_MT` DECIMAL(13,2),`R_AND_D_RESULT_DATE` DATE,`R_AND_D_RESULT` STRING,`R_AND_D_REASON_FOR_REJECTION` STRING,`TRIAL_ORDER_QTY_MT` DECIMAL(13,2),`TRIAL_ORDER_RECEIPT_DATE` DATE,`TRIAL_ORDER_RATE_INR_MT` DECIMAL(13,2),`TRIAL_DATE` DATE,`TRIAL_RESULT_DATE` DATE,`TRIAL_ORDER_RESULT` STRING,`TRIAL_ORDER_REASON_FOR_REJECTION` STRING,`BULK_TRIAL_QTY_MT` DECIMAL(13,2),`BULK_TRIAL_RATE_INR_MT` DECIMAL(13,2),`BULK_ORDER_RECEIPT_DATE` DATE,`BULK_TRIAL_DATE` DATE,`BULK_TRIAL_RESULT_DATE` DATE,`BULK_TRIAL_RESULT` STRING,`BULK_ORDER_REASON_FOR_REJECTION` STRING,`MATERIAL_KEY` BIGINT,`VENDOR_KEY` BIGINT,`PLANT_KEY` BIGINT,`SAMPLE_RECEIPT_DATE_KEY` BIGINT,`R_AND_D_RESULT_DATE_KEY` BIGINT,`TRIAL_ORDER_RECEIPT_DATE_KEY` BIGINT,`TRIAL_DATE_KEY` BIGINT,`TRIAL_RESULT_DATE_KEY` BIGINT,`BULK_ORDER_RECEIPT_DATE_KEY` BIGINT,`BULK_TRIAL_DATE_KEY` BIGINT,`BULK_TRIAL_RESULT_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RM_NEW_VENDOR_DEVELOPMENT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_CEMENT_MAPPING_PLANTS(`RAW_MATERIAL` string,`COMPANY` string,`GROUP_COMPANY` string,`PLANT_LOCATION` string,`PINCODE` string,`PLACE` string,`DISTRICT` string,`STATE` string,`PLANT_TYPE` string,`PLANT_CAPACITY` decimal(13,2),`COMPANY_CAPACITY` decimal(13,2),`VENDOR_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_CEMENT_MAPPING_PLANTS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_NSR_PERCENTAGE(`PRODUCT_MIX` string,`PRODUCT_TYPE` string,`ZONE` string,`PERCENTAGE` decimal(13,4),`PRODUCT_LINE_KEY` BIGINT,`DATE_KEY` BIGINT,`SEGMENT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_NSR_PERCENTAGE'
# MAGIC )
# MAGIC

# COMMAND ----------



# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_WP_NSR_PERCENTAGE(`ZONE` string,`PERCENTAGE` decimal(13,4),`PRODUCT_LINE_KEY` BIGINT,`DATE_KEY` BIGINT,`SEGMENT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_WP_NSR_PERCENTAGE'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_FREIGHT_BUDGET(`FREIGHT_CLASSIFICATION` STRING,`PRODUCT_MIX` STRING,`PRODUCT_TYPE` STRING,`PRODUCT_LINE` STRING,`ZONE` STRING,`BUDGET_PERCENTAGE` DECIMAL(13,2),`PRODUCT_LINE_KEY` BIGINT,`DATE_KEY` BIGINT,`SEGMENT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_FREIGHT_BUDGET'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_WP_FREIGHT_BUDGET(`FREIGHT_CLASSIFICATION` STRING,`ZONE` STRING,`BUDGET_PERCENTAGE` DECIMAL(13,2),`PRODUCT_LINE` STRING,`PRODUCT_LINE_KEY` BIGINT,`DATE_KEY` BIGINT,`SEGMENT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_WP_FREIGHT_BUDGET'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_NSR_DEPOT_EXPENSES(`NSR_EXPENSES` DECIMAL(13,2),`DEPOT_KEY` BIGINT,`DATE_KEY` BIGINT , `PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_NSR_DEPOT_EXPENSES'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC
# MAGIC %sql
# MAGIC create table pro_prod.FACT_NSR_PACKING_COST(`NSR_PACKING_COST` DECIMAL(13,2),`DATE_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_NSR_PACKING_COST'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC
# MAGIC %sql
# MAGIC create table pro_prod.FACT_NSR_DISCOUNTS(`STATE` STRING, `NSR_DISCOUNTS` DECIMAL(13,2),`DATE_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_NSR_DISCOUNTS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_EVA(`HIL` string,`SBU` string,`PRODUCT_LINE` string,`PARTICULARS` string,`ACTUAL_OR_BUDGET` string,`PERCENTAGE` decimal(13,4),`DATE_KEY` BIGINT)USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_EVA'
# MAGIC )

# COMMAND ----------

# MAGIC
# MAGIC %sql
# MAGIC create table pro_prod.FACT_EVA_GROWTH_DEGROWTH(`HIL` string,`SBU` string,`MIS_PRODUCT_LINE` STRING,`PARTICULARS` string,`ACTUAL_OR_BUDGET` string,`PERCENTAGE` decimal(13,4),`REVENUE` decimal(23,2),`REVENUE_YTD` decimal(33,2) , `DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_EVA_GROWTH_DEGROWTH'
# MAGIC )

# COMMAND ----------

# MAGIC
# MAGIC %sql
# MAGIC create table pro_prod.FACT_BOM_TARGETS(`PER_PRODUCTION_MT_TARGET` decimal(13,2),`DATE_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT)USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_BOM_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_COST_COLLECTIONS(`DOCUMENT_NO` STRING,`YEAR` STRING,`AMOUNT` decimal(13,2),`GEO_KEY` BIGINT,`POSTING_DATE_KEY` BIGINT,`CUSTOMER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_COST_COLLECTIONS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_OTHER_COST_ACTUALS(`PARTICULARS` STRING,`PF_CATEGORY` STRING,`SEGMENT` STRING,`ACTUAL_VALUE` DECIMAL(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_OTHER_COST_ACTUALS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_OTHER_COST_TARGETS(`PARTICULARS` STRING,`SEGMENT` STRING,`TARGET_VALUE` DECIMAL(13,6),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_OTHER_COST_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.DIM_GL_MASTER(`GL_DESCRIPTION` STRING,`GL_GROUP` STRING,`GL_CODE` STRING,`GL_CODE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_GL_MASTER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_OTHER_COST_ALLOCATION(`SEGMENT` string,`PRODUCT_TYPE` string,`COST_VALUE` decimal(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_OTHER_COST_ALLOCATION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_CONVERSION_COST_TARGETS_PRODUCT_TYPE(`PRODUCT_TYPE` STRING,`PARTICULARS` STRING,`MEASURE` STRING,`UOM` STRING,`TARGET` DECIMAL(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_CONVERSION_COST_TARGETS_PRODUCT_TYPE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_CONVERSION_COST_TARGETS_PF_CATEGORY(`PF_CATEGORY` STRING,`PARTICULARS` STRING,`MEASURE` STRING,`UOM` STRING,`TARGET` DECIMAL(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_CONVERSION_COST_TARGETS_PF_CATEGORY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_MIS_TARGET_MASTER(`MATERIAL_CATEGORY` STRING,`UOM` STRING,`TARGET_VALUE` DECIMAL(13,2),`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_MIS_TARGET_MASTER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_MIS_CAPACITY(`PF_CATEGORY` STRING,`UOM` STRING,`CAPACITY` DECIMAL(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_MIS_CAPACITY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PUTTY_RM_DISCOUNTS(`DISCOUNT` STRING,`DISCOUNT_VALUE` DECIMAL(13,2),`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PUTTY_RM_DISCOUNTS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PUTTY_MIS_KPI_TARGETS(`MONTH_OF_YEAR` STRING, `LABOUR_COST_INR_PER_MT` DECIMAL(13,2),`OTHER_FIXED_COST_INR_PER_MT` DECIMAL(13,2),`POWER_FUEL_INR_PER_MT` DECIMAL(13,2),`PRE_PACKING_COST_INR_PER_MT` DECIMAL(13,2),`PRODUCTION_MT` DECIMAL(13,2),`PRODUCT_COST_INR_PER_MT` DECIMAL(13,2),`SALES_MT` DECIMAL(13,2),`SECONDARY_PACKING_COST_INR_PER_MT` DECIMAL(13,2),`STORES_SPARES_INR_PER_MT` DECIMAL(13,2),`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PUTTY_MIS_KPI_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PUTTY_MIS_OTHER_COST_BUDGET(`BUDGET_VALUE` decimal(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT,`GL_CODE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PUTTY_MIS_OTHER_COST_BUDGET'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PUTTY_MIS_CONVERSION_COST_ACTUALS(`PARTICULARS` string,`CONVERSION_COST_VALUE` decimal(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PUTTY_MIS_CONVERSION_COST_ACTUALS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PUTTY_MIS_TARGET_MASTER(`TARGET_VALUE` decimal(13,2),`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PUTTY_MIS_TARGET_MASTER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_GL_ACCOUNT(`FISCAL_YEAR` STRING,`AMOUNT` DECIMAL(15,2),`TEXT` STRING,`QUANTITY` DECIMAL(13,3), `GL_CODE_KEY` BIGINT,`PLANT_KEY` BIGINT,`BUSINESS_AREA_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_GL_ACCOUNT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_SALES_TRACKER(`SBU` STRING,`PRODUCT_LINE` STRING,`PERC_TARGET_VALUE` DECIMAL(13,2),`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SALES_TRACKER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_MATERIAL_USAGE (`CONSUMED_QUANTITY` DECIMAL(34,9),`CONSUMED_VALUE` DECIMAL(15,2),`PRODUCTION_QUANTITY` DECIMAL(34,9),`PRODUCTION_VALUE` DECIMAL(15,2),`SCRAP_QUANTITY` decimal(34,9),`SCRAP_QUANTITY_VALUE` decimal(15,2),`CONSUMED_QUANTITY_MT` DECIMAL(38,13),`PRODUCTION_QUANTITY_MT` DECIMAL(38,13),`SCRAP_QUANTITY_MT` decimal(38,13),`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`SAP_CLOSING_ADJ_DATE_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_MATERIAL_USAGE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PLANT_SALES_TARGETS (`TARGET_VALUE` DECIMAL(13,2),`PLANT_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PLANT_SALES_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_MIS_SUMMARY (`HIL` STRING,`SBU` STRING,`PRODUCT_LINE` STRING,`PLANT` STRING,`ACTUAL_OR_BUDGET` STRING,`PRODUCTION` DECIMAL(13,2),`SALES` DECIMAL(13,2),`GROSS_REVENUE` DECIMAL(13,2),`DISCOUNT_COMMISSION` DECIMAL(13,2),`REVENUE` DECIMAL(13,2),`FREIGHT` DECIMAL(13,2),`PACKING` DECIMAL(13,2),`TOTAL_DISTRIBUTION_EXPENSES` DECIMAL(13,2),`NET_SALES_REALISATION` DECIMAL(13,2),`MISC_RECEIPTS` DECIMAL(13,2),`SERV_TO_OTHER_DIVNS` DECIMAL(13,2),`FOB_SALE_TO_AEROCON` DECIMAL(13,2),`TOTAL_OTHER_INCOME` DECIMAL(13,2),`TOTAL_INCOME_SALES_INCOME` DECIMAL(13,2),`INC_DEC_IN_INVENTORY` DECIMAL(13,2),`PRODUCTION_VALUE` DECIMAL(13,2),`IMPORTED_RAW_MATERIAL` DECIMAL(13,2),`INDIGENOUS_RAW_MATERIAL` DECIMAL(13,2),`TRADED_GOODS` DECIMAL(13,2),`TOTAL_RAW_MATERIAL` DECIMAL(13,2),`STORES_SPARES` DECIMAL(13,2),`POWER_FUEL` DECIMAL(13,2),`WAGES_BENEFITS` DECIMAL(13,2),`GRM` DECIMAL(13,2),`CONTRACT_WAGES` DECIMAL(13,2),`TOTAL_OF_OTHER_VARIABLE_EXP_EXCLUDING_RM` DECIMAL(13,2),`TOTAL_MATERIAL_COST_VERIABLE_COST` DECIMAL(13,2),`CONTRIBUTION` DECIMAL(13,2),`REPAIRS_TO_BUILDINGS` DECIMAL(13,2),`SALARIES_BENEFITS` DECIMAL(13,2),`INSURANCE` DECIMAL(13,2),`VEHICLE_EXPENSES` DECIMAL(13,2),`COMMUNICATION_EXPENSES` DECIMAL(13,2),`G_CHARGES` DECIMAL(13,2),`TRAV_CONV` DECIMAL(13,2),`RATE_TAXES` DECIMAL(13,2),`TOTAL_OTHER_MFG_EXPENSES` DECIMAL(13,2),`R_D_EXPENSES` DECIMAL(13,2),`C_O_EXPENSES_APPORTIONED` DECIMAL(13,2),`TOTAL_MANUFACTURING_OVERHEADS` DECIMAL(13,2),`TOTAL_MANUFACTURING_EXP` DECIMAL(13,2),`SGA` DECIMAL(13,2),`RENT_RATES_TAXES` DECIMAL(13,2),`EXCISE_DUTY_ON_CLOSING_STOCK` DECIMAL(13,2),`MARKETING_STAFF_SALARIES_AND_BENEFITS` DECIMAL(13,2),`DIRECTORS_AUDITORS_FEES` DECIMAL(13,2),`SAG_VEHICLES_EXPENSES` DECIMAL(13,2),`SAG_COMMUNICATION_EXPENSES` DECIMAL(13,2),`ADVERTISEMENT` DECIMAL(13,2),`GENERAL_CHARGES` DECIMAL(13,2),`TRAVELLING_CONVEYANCE` DECIMAL(13,2),`SAG_C_O_EXPENSES_APPORTIONED` DECIMAL(13,2),`TOTAL_SELLING_ADMN_GEN_EXP` DECIMAL(13,2),`HIL_C_O_EXPENSES_APPORTIONED` DECIMAL(13,2),`TOTAL_EXPENSES` DECIMAL(13,2),`PBIDT` DECIMAL(13,2),`GRP_C_O_EXPENSES_APPORTIONED` DECIMAL(13,2),`EBITDA` DECIMAL(13,2),`INTEREST_LONG_TERM` DECIMAL(13,2),`INTEREST_SHORT_TERM` DECIMAL(13,2),`C_O_INTEREST_APPORTIONED` DECIMAL(13,2),`TOTAL_INTEREST` DECIMAL(13,2),`PBDT` DECIMAL(13,2),`DEPRECIATION` DECIMAL(13,2),`C_O_SHARE_APPORTIONED` DECIMAL(13,2),`TOTAL_DEPRECIATION` DECIMAL(13,2),`OPERATING_PROFIT` DECIMAL(13,2),`OTHER_NON_OPERATING_INCOME` DECIMAL(13,2),`NON_OPERATING_EXPENSES` DECIMAL(13,2),`PBT` DECIMAL(13,2),`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_MIS_SUMMARY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_MATERIAL_VARIANCE(`PRODUCTION_ORDER` string,`PROD_ORD_TYPE` string,`PRODUCTION_QTY_KG` decimal(38,9),`FG_AMOUNT` decimal(23,2),`FG_STANDARD_WT` decimal(18,6),`RM_ACTUAL_QTY_KG` decimal(38,9),`RM_AMOUNT` decimal(23,2),`RM_QUANTITY` decimal(23,3),`RM_RATE_PER_KG` decimal(38,8),`STD_BOM_QTY` decimal(38,6),`STD_QUANTITY` decimal(23,3),`FG_QUANTITY` decimal(23,3),`STD_BOM_QTY_BASE_UOM` decimal(38,15),`STD_BOM_FOR_100_KG` decimal(38,6),`STD_RM_REQUIRED_QTY` decimal(38,6),`STD_RM_REQUIRED_VALUE` decimal(38,6),`TARGET_PRICE` decimal(13,2),`QTY_VARIANCE` decimal(38,6),`RATE_VARIANCE` decimal(38,6),`LAST_EXECUTED_TIME` string,`SNAPSHOT_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`FG_MATERIAL_KEY` BIGINT,`RM_MATERIAL_KEY` BIGINT,`REPORTING_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_MATERIAL_VARIANCE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_NONPRODUCTION_MATERIAL_VARIANCE(`FG_MATERIAL_GROUP` string,`RM_MATERIAL_GROUP` string,`UOM` string,`RM_MATERIAL_ID` string,`MATERIAL_DESCRIPTION` string,`RM_QUANTITY` decimal(38,6),`RM_AMOUNT` decimal(38,6),`PP_OR_CONSUMABLES` string,`TARGET_PRICE` decimal(13,2),`LAST_EXECUTED_TIME` string,`SNAPSHOT_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`REPORTING_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_NONPRODUCTION_MATERIAL_VARIANCE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PUTTY_MATERIAL_VARIANCE (`PRODUCTION_ORDER` string,`PROD_ORD_TYPE` string,`PRODUCTION_QTY_KG` decimal(35,9),`FG_AMOUNT` decimal(23,2),`RM_ACTUAL_QTY_KG` decimal(35,9),`RM_AMOUNT` decimal(38,6),`RM_RATE_PER_KG` decimal(38,8),`STD_QTY_KG` decimal(13,2),`STD_QTY_FOR_ACTUAL_PROD` decimal(38,6),`STD_RM_REQUIRED_VALUE` decimal(38,6),`TARGET_PRICE` decimal(13,2),`QTY_VARIANCE` decimal(38,6),`RATE_VARIANCE` decimal(38,6),`LAST_EXECUTED_TIME` string,`REPORTING_DATE_KEY` BIGINT,`FG_MATERIAL_KEY` BIGINT,`SNAPSHOT_DATE_KEY` BIGINT,`PLANT_KEY` BIGINT,`RM_MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PUTTY_MATERIAL_VARIANCE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_WC_ROCE_CCC (`HIL` string,`SBU` string,`PARTICULARS` string,`BUDGET` decimal(13,2),`ACTUAL` decimal(13,2),`SORT` integer,`PRODUCT_LINE` string,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_WC_ROCE_CCC'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_WC_ROCE (`HIL` STRING,`SBU` STRING,`ACTUAL_OR_BUDGET` STRING,`CASH_AND_BANK_BALANCES` DECIMAL(13,2),`RAW_MATERIALS_COMPONENTS_IMPORTED` DECIMAL(13,2),`RAW_MATERIALS_COMPONENTS_INDIGENOUS` DECIMAL(13,2),`STORES_SPARES` DECIMAL(13,2),`STOCK_IN_PROCESS` DECIMAL(13,2),`FINISHED_GOODS` DECIMAL(13,2),`STOCK_IN_TRADE` DECIMAL(13,2),`INVENTORIES` DECIMAL(13,2),`RECEIVABLES` DECIMAL(13,2),`ADVANCES` DECIMAL(13,2),`DEPOSITS` DECIMAL(13,2),`OTHER_CURRENT_ASSETS_PRE` DECIMAL(13,2),`TOTAL_CURRENT_ASSETS` DECIMAL(13,2),`ACCOUNTS_PAYABLE_IMPORT` DECIMAL(13,2),`ACCOUNTS_PAYABLE_DOMESTIC` DECIMAL(13,2),`DEPOSITS_AND_ADVANCES` DECIMAL(13,2),`OTHER_CURRENT_LIABILITIES_PRE` DECIMAL(13,2),`TOTAL_CURRENT_LIABILITIES` DECIMAL(13,2),`NCA` DECIMAL(13,2),`GROSS_BLOCK` DECIMAL(13,2),`ADDITION_DELETION_DURING_THE_YEAR` DECIMAL(13,2),`TOTAL_GROSS_BLOCK` DECIMAL(13,2),`LESS_ACCUMLATED_DEPRECIATION` DECIMAL(13,2),`NET_FIXED_ASSETS` DECIMAL(13,2),`NET_CAPITAL_EMPLOYEED` DECIMAL(13,2),`REVENUE_NET_OF_DISCOUNT` DECIMAL(13,2),`EBIT` DECIMAL(13,2),`ROCE` DECIMAL(13,2),`WORKING_CAPITAL_TO_REVENUE` DECIMAL(13,2),`OTHER_CURRENT_ASSETS` DECIMAL(15,2),`OTHER_CURRENT_LIABILITIES` DECIMAL(14,2),`ACCOUNTS_PAYABLE` DECIMAL(14,2),`PRODUCT_LINE` STRING,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_WC_ROCE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_MIS_INVENTORY (`OPENING_QTY` decimal(13,3),`BASE_UNIT` string,`OPENING_VALUE` decimal(11,2),`OPENING_QTY_KG` decimal(32,9),`STOCK_TAKING_DATE` date,`LAST_EXECUTED_TIME` string,`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT,`SNAPSHOT_DATE_KEY` BIGINT,`STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_MIS_INVENTORY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_OVERDUE_AMOUNT (`OVERDUE_AMOUNT` decimal(38,2),`GEO_KEY` BIGINT,`PER_KEY` BIGINT,`CUSTOMER_KEY` BIGINT,`SNAPSHOT_DATE_KEY` BIGINT,`SALES_TYPE_KEY` BIGINT,`PRODUCT_LINE_KEY` BIGINT,`SALES_ORG_KEY` BIGINT,`DIVISION_KEY` BIGINT,`LAST_EXECUTED_TIME` timestamp,`LAST_EXECUTED_DATE` date)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_OVERDUE_AMOUNT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.DIM_PURCHASE_ORG(`PURCHASE_ORG` STRING,`DESCRIPTION` STRING,`COMPANY_CODE` STRING,`PURCHASE_ORG_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PURCHASE_ORG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.DIM_PURCHASE_GROUP(`PURCHASE_GROUP` STRING,`DESCRIPTION` STRING,`PURCHASE_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_PURCHASE_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_MARD_QUANTITY(`UNREST_QTY` decimal(13,3), `MEINH` STRING,`UMREZ` decimal(5,0),`UMREN` decimal(5,0),`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_MARD_QUANTITY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_DEFICIT_TREND(`RM_GROUP` STRING,`PLANNED_PRODUCTION` decimal(21,2), `RM_PER_UNIT` decimal(13,6),`REQUIRED_RM_FOR_PRODUCTION` decimal(35,8),`EOD_STOCK_QTY` decimal(38,7),`QTY` decimal(23,3),`PRODUCT_LINE_KEY` BIGINT,`PLANT_KEY` BIGINT,`STOCK_DATE_KEY` BIGINT,`PROCESSED_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_DEFICIT_TREND'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PO_VENDOR_PERFORMANCE(`VENDOR_KEY` long,`PURCHASE_DOCUMENT` string,`DOCUMENT_DATE_KEY` long,`PURCHASE_ORG_KEY` long,`PURCHASE_GROUP_KEY` long,`PO_TYPE` string,`VENDOR_PERFORMANCE` double,`PLANT_KEY` long)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PO_VENDOR_PERFORMANCE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_INVENTORY(`STORAGE_LOCATION` string,`UNREST_QTY` decimal(13,3),`QUALITY_QTY` decimal(13,3),`BLOCKED_QTY` decimal(13,3),`IN_TRANSIT_QTY` decimal(14,3),`MT_CONV_VALUE` decimal(23,11),`CUM_CONV_VALUE` decimal(11,6),`PRICE` decimal(11,2),`LAST_EXECUTED_TIME` STRING,`MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT,`SNAPSHOT_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_INVENTORY'
# MAGIC )

# COMMAND ----------

ASPIRE_GL_BUDGETS_TRANSASPIRE_GL_BUDGETS_TRANS%sql
create table pro_prod.FACT_RM_CONSUMPTION_ASPIRE (`RM_GROUP` string,`RM_GROUP2` string,`RM_AMOUNT_IN_LC` decimal(23,2),`RM_QUANTITY` decimal(23,3),`RM_QUANTITY_MT` decimal(38,14),`BUDGET_QTY` decimal(23,2),`BUDGET_RATE` decimal(23,2),`PLANT_KEY` long,`POSTING_DATE_KEY` long)
USING PARQUET
OPTIONS(
`compression` 'snappy',
path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RM_CONSUMPTION_ASPIRE'
)

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_ASPIRE_BUDGETS_OTHERS (`GROUP` STRING,`PARTICULARS` STRING,`TARGET` DECIMAL(13,6),`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_ASPIRE_BUDGETS_OTHERS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PO_HEADER_CHANGE_AGGREGATE (`PURCHASE_DOC_NUMBER` STRING,`DATE_KEY` BIGINT,`NO_OF_PRICE_CHANGES` BIGINT,`NO_OF_QUANTITY_CHANGES` BIGINT,`PLANT_KEY` BIGINT, `DOC_TYPE` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS(
# MAGIC `compression` 'snappy',
# MAGIC path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PO_HEADER_CHANGE_AGGREGATE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`DIM_CHAPTER_CREATED` (`CHAPTER_ID` string,`CREATED_DATE` date)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_CHAPTER_CREATED'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_SALES_ORDERS_AGG` (`ORDER_QUANTITY` decimal(25,3),`ORDER_QTY_CONV` decimal(38,14),`PLANT_KEY` long,`MATERIAL_KEY` long,`CREATED_DATE_KEY` long)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_SALES_ORDERS_AGG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_CHAPTER_CHANGES` (`CHAPTER_ID` string,`UPDATED_DATE` date)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_CHAPTER_CHANGES'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_ASPIRE_ACTUALS` (`GROUP` STRING,`PARTICULARS` STRING,`ACTUAL_VALUE` DECIMAL(13,6),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_ASPIRE_ACTUALS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_ASPIRE_GL_BUDGETS` (`GL_GROUP` STRING,`UOM` STRING,`TARGET` DECIMAL(13,6),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_ASPIRE_GL_BUDGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_ASPIRE_BUDGETS_OTHERS_TRANS` (`BRIQUETTE_COAL_BIOMASS_AVG_COST_INR_KG` decimal(23,6),`BRIQUETTE_COAL_BIOMASS_COST_INR_MT_OR_CUM` decimal(23,6),`BRIQUETTE_COAL_BIOMASS_NO_OF_KG_MT_OR_CUM` decimal(23,6),`BRIQUETTE_COAL_BIOMASS_O_M_CHARGES` decimal(23,6),`COAL_CESS_CHARGES_INR_MT_OR_CUM` decimal(23,6),`FURNACE_OIL_AVG_COST_INR_L` decimal(23,6),`FURNACE_OIL_NO_OF_L_MT_OR_CUM` decimal(23,6),`NET_LOSS_PERCENTAGE` decimal(23,6),`POWER_AVG_VARIABLE_COST_UNIT` decimal(23,6),`POWER_COST_MT_OR_CUM` decimal(23,6),`POWER_NO_OF_UNITS_MT_OR_CUM` decimal(23,6),`PRODUCTION` decimal(23,6),`DATE_KEY` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_ASPIRE_BUDGETS_OTHERS_TRANS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_ASPIRE_GL_BUDGETS_TRANS` (`CONTRACT_LABOUR` decimal(23,6),`GENERAL_REPAIRS_AND_MAINTENANCE` decimal(23,6),`LABOUR` decimal(23,6),`PACKING` decimal(23,6),`STORES_AND_SPARES` decimal(23,6),`WAGES_AND_BENEFITS` decimal(23,6),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_ASPIRE_GL_BUDGETS_TRANS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_VENDOR_MASTER_LOG` (`CHANGES_COUNT` BIGINT,`UNBLOCK_CHANGES` BIGINT,`BLOCK_CHANGES` BIGINT,`UNDEL_CHANGES` BIGINT,`DEL_CHANGES` BIGINT,`CHANGED_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_VENDOR_MASTER_LOG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`VISIT_FREQUENCY` (`PRODUCT_TYPE` string,`STATE_DESC` string,`FY_NAME_DISPLAY` BIGINT,`EFFECTIVE_CUSTOMER_NAME` string,`NAME1` string,`SECONDARY_CUSTOMER` string,`PARTY_NAME` string,`VISIT_COUNT` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/VISIT_FREQUENCY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_PLANT_LEVEL_VENDOR` (`IN_ACTIVE` BIGINT,`ACTIVE` BIGINT,`PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PLANT_LEVEL_VENDOR'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`FACT_VENDOR_PAYMENT_TERMS` (`PAYMENT_TERM` STRING,`DAY_LIMIT` STRING,`PAYMENT_TERM_DESCRIPTION` STRING,`COUNT` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_VENDOR_PAYMENT_TERMS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`DIM_STATE` (`STATE` STRING,`ZONE_SBU1` STRING,`ZONE_SBU2` STRING,`ZONE_SBU3` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_STATE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_prod`.`DIM_MIS_PRODUCT_LINE` (`HIL` STRING,`SBU` STRING,`PRODUCT_LINE` STRING,`PLANT_NAME` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/DIM_MIS_PRODUCT_LINE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_PF_MIS_FIXED_COST_BUDGETS(`TARGET` decimal(13,2),`PLANT_KEY` BIGINT,`DATE_KEY` BIGINT,`GL_CODE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_PF_MIS_FIXED_COST_BUDGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_OUTSTANDING_AND_COLLECTIONS(`SBU` string,`PRODUCT_LINE_FOR_OUTSTANDING` string,`SALE_TYPE` string,`OVERDUE_PERIOD_START_IN_DAYS` decimal(13,2),`DIVISION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_OUTSTANDING_AND_COLLECTIONS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC create table pro_prod.FACT_RM_MATERIAL_USAGE_SBU2(`PRODUCTION_ORDER` string,`MOVEMENT_TYPE` string,`RM_AMOUNT_IN_LC` decimal(13,2),`RM_QUANTITY` decimal(13,3),`BASE_UNIT_OF_MEASURE` string,`RM_QUANTITY_MT` decimal(30,14),`RM_MATERIAL_KEY` BIGINT,`PLANT_KEY` BIGINT,`POSTING_DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT_RM_MATERIAL_USAGE_SBU2'
# MAGIC )
