# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_business_address` (`ADDR_NUM` STRING, `TITLE` STRING, `NAME1` STRING, `CITY1` STRING, `POST_CODE1` STRING, `STR_SUPPL1` STRING, `LOCATION` STRING, `COUNTRY_KEY` STRING, `TEL_NUM` STRING, `ADDR_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_BUSINESS_ADDRESS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_customer` (`CUST_ID` STRING, `COUNTRY` STRING, `NAME1` STRING, `NAME2` STRING, `CITY` STRING, `POSTAL_CODE` STRING, `REGION` STRING, `TELF_NUMBER` STRING, `ONE_TIME_ACCOUNT` STRING, `ADDRESS` STRING, `TITLE` STRING, `CUST_ACCT_GRP` STRING, `CTRL_DELV_BLOCK` STRING, `DISTRICT` STRING, `LANG` STRING, `VAT_REG_NUM` STRING, `PLANT` STRING, `TAX_TYPE` STRING, `TAX_NUM_TYPE` STRING, `GSTN_ID` STRING, `NAME_REPRESENTATIVE` STRING, `BUSINESS_TYPE` STRING, `INDUSTRY_TYPE` STRING, `CUSTOMER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_CUSTOMER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_customer_group` (`CUSTOMER_GROUP_ID` STRING, `CUSTOMER_GROUP_NAME` STRING, `CUSTOMER_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_CUSTOMER_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_date` (`DATE_DT` DATE, `DATE_ID` BIGINT, `DAY_ID` BIGINT, `DAY_NAME` STRING, `DAY_OF_MONTH_NUM` BIGINT, `DAY_OF_YR_NUM` BIGINT, `FY_DAY_OF_MONTH` STRING, `FY_HF_YR_OF_YR` STRING, `FY_HY_NAME` STRING, `FY_MONTH_ID` BIGINT, `FY_MONTH_OF_YR` STRING, `FY_MONTH_OF_YR_NUM` BIGINT, `FY_NAME` BIGINT, `FY_QTR_ID` BIGINT, `FY_QTR_NAME` STRING, `FY_QTR_OF_YR` STRING, `FY_QTR_OF_YR_NUM` BIGINT, `FY_WEEK_ID` BIGINT, `FY_WEEK_OF_YR_NUM` BIGINT, `FY_WK_OF_MONTH_NAME` STRING, `MONTH_ID` BIGINT, `MONTH_OF_YR_NAME` STRING, `MONTH_OF_YR_NUM` BIGINT, `QTR_ID` BIGINT, `QTR_OF_YR_NUM` BIGINT, `WEEK_ID` BIGINT, `WEEK_OF_YR_NUM` BIGINT, `WK_NAME` STRING, `YR_NAME` BIGINT, `WK_SORT` BIGINT, `DATE_CREATED_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_DATE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC CREATE TABLE `pro_dev`.`dim_distribution_channel` (`DISTRIBUTION_CHANNEL` STRING, `DISTRIBUTION_CHANNEL_DESCRIPTION` STRING, `DIST_CHANNEL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_DISTRIBUTION_CHANNEL'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_division` (`DIVISION_ID` STRING, `DIVISION_NAME` STRING, `DIVISION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_DIVISION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_first_time_sales` (`FIRST_CUST_FLAG` BIGINT, `FIRST_CUST_PRD_SALES_FLAG` BIGINT, `FIRST_PRD_SALES_FLAG` BIGINT, `FIRST_TIME_SALES_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_FIRST_TIME_SALES'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_freight_group` (`MAT_FRGHT_GRP` STRING, `DESCRIPTION` STRING, `MAT_FRGROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_FREIGHT_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_hysil_customers` (`CUSTOMER_CODE` STRING)
# MAGIC USING com.databricks.spark.csv
# MAGIC OPTIONS (
# MAGIC   `multiLine` 'false',
# MAGIC   `escape` '"',
# MAGIC   `header` 'true',
# MAGIC   `delimiter` ',',
# MAGIC   path 'dbfs:/FileStore/tables/HYSIL_CUSTOMERS.csv'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_personnel` (`PER_NUMBER` STRING, `COMP_CODE` STRING, `PER_AREA` STRING, `EMP_GROUP` STRING, `EMP_SUBGROUP` STRING, `ORG_KEY` STRING, `BUS_AREA` STRING, `COST_CENTER` STRING, `ORG_UNIT` STRING, `POSITION` STRING, `JOB` STRING, `PER_NAME` STRING, `CTRL_AREA` STRING, `FUNDS_CTR` STRING, `FUND` STRING, `FUNC_AREA` STRING, `SEGMENT` STRING, `PER_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PERSONNEL'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_plant_depot` (`PLANT_ID` STRING, `PLANT_NAME` STRING, `VALUATION_AREA` STRING, `FACTORY_CAL_KEY` STRING, `PLANT_NAME_2` STRING, `POSTAL_CODE` STRING, `PURCHASE_ORG` STRING, `SALES_ORG` STRING, `COUNTRY` STRING, `REGION` STRING, `ADDRESS` STRING, `DISTRIBUTION_CHANNEL` STRING, `DIVISION` STRING, `LANGUAGE` STRING, `PLANT_CATEGORY` STRING, `SALES_DISTRICT` STRING, `BUSINESS_PLACE` STRING, `STORE_TYPE` STRING, `DEP_STORE` STRING, `DEPOT_ID` STRING, `IS_PLANT` INT, `REPORT_PLANT_ID` STRING, `REPORT_PLANT_NAME` STRING, `IS_ACTIVE` INT, `FPR_EMPLOYEE_ID` STRING, `PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PLANT_DEPOT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_pricing_group` (`PRICE_GROUP_ID` STRING, `PRICE_GROUP_DESCRIPTION` STRING, `CUST_PRICING_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PRICING_GROUP'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_product` (`MATERIAL_NUMBER` STRING, `MATERIAL_GROUP` STRING, `UNIT_OF_MEASURE` STRING, `DIVISION` STRING, `ASSEMBLY_TYPE` STRING, `BRAND` STRING, `CATEGORY` STRING, `CHANNEL` STRING, `COLOUR` STRING, `COLOUR_TYPE` STRING, `FITTINGS_TYPE` STRING, `LENGTH` STRING, `PRODUCT_GROUP` STRING, `PRODUCT_LINE` STRING, `PRODUCT_MIX` STRING, `PRODUCT_TYPE` STRING, `SBU` STRING, `SIZE` STRING, `SOCKET_TYPE` STRING, `SUB_CATEGORY` STRING, `THICKNESS` STRING, `WIDTH` STRING, `SKU_NUMBER` INT, `MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PRODUCT'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_product_group` (`MATERIAL_GROUP_ID` STRING, `MATERIAL_GROUP_DESCRIPTION` STRING, `MATERIAL_GROUP_DESCRIPTION_2` STRING, `MATERIAL_GROUP_KEY` BIGINT)
# MAGIC USING parquet
# MAGIC OPTIONS (
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PRODUCT_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_product_group_derived` (`PRODUCT_SUB_GROUP` STRING, `PRODUCT_GROUP` STRING, `PRODUCT_LINE` STRING, `SALES_ORG` STRING, `PRODUCT_SUB_GROUP_KEY` BIGINT)
# MAGIC USING parquet
# MAGIC OPTIONS (
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PRODUCT_GROUP_DERIVED'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_product_line` (`PRODUCT_LINE` STRING, `DESCRIPTION` STRING, `PRODUCT_LINE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PRODUCT_LINE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_product_pricing_group` (`MAT_PRCNG_GRP` STRING, `DESCRIPTION` STRING, `MATL_PRICING_GROUP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_PRODUCT_PRICING_GROUP'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_route` (`ROUTE` STRING, `DESCRIPTION` STRING, `ROUTE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_ROUTE'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_sale_type` (`SALES_TYPE` STRING, `SALES_TYPE_DESC` STRING, `SALES_TYPE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_SALE_TYPE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_sales_group` (`SALES_GROUP` STRING, `DESCRIPTION` STRING, `SALES_GRP_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_SALES_GROUP'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_sales_office` (`SALES_OFFICE` STRING, `DESCRIPTION` STRING, `SALES_OFC_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_SALES_OFFICE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_sales_org` (`SALES_ORG` STRING, `STATS_CURR` STRING, `COMPANY_CODE` STRING, `ADDRESS_ID` STRING, `ADDR_TXT_NAME` STRING, `LTTR_HDR_TXT_NAME` STRING, `FTTR_LINES_TXT` STRING, `GRTNG_TXT_NAME` STRING, `REF_SALES_ORG` STRING, `CUST_ID` STRING, `REB_PROC_ACTV` STRING, `SALES_ORG_CAL` STRING, `PUR_ORG` STRING, `PUR_GRP` STRING, `VNDR_ACC_NO` STRING, `PLANT_ID` STRING, `ORD_TYP` STRING, `PUR_DOC_CAT` STRING, `MV_TYP` STRING, `STRG_LOC` STRING, `TXT_SDS_SNDR` STRING, `TAX_NUM` STRING, `VAT_REG_NUM` STRING, `NUMB_TIM` STRING, `MAX_BLLNG_DOC` STRING, `PRC_PRTCN_PRD` STRING, `PRC_PRTCN_UNT` STRING, `SALES_ORG_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_SALES_ORG'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_sate` (`DATE_DT` DATE, `DATE_ID` BIGINT, `DAY_ID` BIGINT, `DAY_NAME` STRING, `DAY_OF_MONTH_NUM` BIGINT, `DAY_OF_YR_NUM` BIGINT, `FY_DAY_OF_MONTH` STRING, `FY_HF_YR_OF_YR` STRING, `FY_HY_NAME` STRING, `FY_MONTH_ID` BIGINT, `FY_MONTH_OF_YR` STRING, `FY_MONTH_OF_YR_NUM` BIGINT, `FY_NAME` BIGINT, `FY_QTR_ID` BIGINT, `FY_QTR_NAME` STRING, `FY_QTR_OF_YR` STRING, `FY_QTR_OF_YR_NUM` BIGINT, `FY_WEEK_ID` BIGINT, `FY_WEEK_OF_YR_NUM` BIGINT, `FY_WK_OF_MONTH_NAME` STRING, `MONTH_ID` BIGINT, `MONTH_OF_YR_NAME` STRING, `MONTH_OF_YR_NUM` BIGINT, `QTR_ID` BIGINT, `QTR_OF_YR_NUM` BIGINT, `WEEK_ID` BIGINT, `WEEK_OF_YR_NUM` BIGINT, `WK_NAME` STRING, `YR_NAME` BIGINT, `DATE_CREATED_KEY` BIGINT, `WK_SORT` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_DATE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_storage_location` (`PLANT_ID` STRING, `STORAGE_LOCATION` STRING, `DESCRIPTION` STRING, `STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_STORAGE_LOCATION'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`dim_territory` (`SALES_ORG` STRING, `PRODUCT_LINE` STRING, `SALE_TYPE` STRING, `PINCODE` STRING, `DISTRICT` STRING, `SALES_GROUP` STRING, `STATE` STRING, `ZONE` STRING, `COUNTRY` STRING, `GEO_DISTRICT` STRING, `GEO_STATE` STRING, `PINCODE_TXT` STRING, `DISTRICT_TXT` STRING, `SALES_GROUP_TXT` STRING, `STATE_TXT` STRING, `ZONE_TXT` STRING, `COUNTRY_TXT` STRING, `RLS` STRING, `GEO_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/DIM_TERRITORY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_depot_netloss` (`MOVEMENT_TYPE` STRING, `MATL_KEY` STRING, `MATL_DOC` STRING, `MATL_DOC_YEAR` STRING, `DOC_ITEM` STRING, `QTY_KEY` DECIMAL(13,3), `UNIT_WEIGHTS` DECIMAL(11,6), `TOTAL_UNIT_WEIGHTS` DECIMAL(25,9), `WEIGHTS_MT` DECIMAL(30,14), `NET_LOSS_MT` DECIMAL(30,14), `DATE_KEY` BIGINT, `PLANT_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_DEPOT_NETLOSS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC CREATE TABLE `pro_dev`.`fact_inventory` (`PURCH_GRP` STRING, `MATL_TYPE` STRING, `UNIT_MEASURE` STRING, `NAME1` STRING, `BLKD_QTY` DECIMAL(13,3), `QLTY_QTY` DECIMAL(13,3), `RTRNS_QTY` DECIMAL(13,3), `REST_QTY` DECIMAL(13,3), `UNREST_QTY` DECIMAL(13,3), `TRSN_QTY` DECIMAL(13,3), `TOTAL_MT` DECIMAL(35,14), `RECLAIMABLE_QTY` DECIMAL(30,14), `DESTROYABLE_QTY` DECIMAL(36,14), `IN_TRANSIT_QTY` DECIMAL(30,14), `GOOD_QTY` DECIMAL(30,14), `STOCK_CURING` DECIMAL(30,14), `STOCK_TAKING_DATE` DATE, `PLANT_KEY` BIGINT, `MATL_KEY` BIGINT, `SNAPSHOT_DATE_KEY` BIGINT, `STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT_INVENTORY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_daily_seasonal_plan` (`BILLING_MONTH` STRING, `STC_PLAN` BIGINT, `STC_ACTUAL` DECIMAL(38,11), `TOTAL_SALES_PLAN` BIGINT, `TOTAL_SALES` DECIMAL(38,8), `BALANCE_DISPATCH` DECIMAL(38,6), `PLANT_DAILY_SALE_PLAN` DOUBLE, `DAILY_STO_PLAN` DOUBLE, `GOOD_QTY_SUM` DECIMAL(38,14), `OPENING_STOCK` DECIMAL(38,13), `IS_PLANT` INT, `PRODUCTION_PLAN` BIGINT, `NET_STOCK_CUMM` DOUBLE, `CLOSING_INVENTORY` DOUBLE, `DEPOT_DAILY_SALE_PLAN` DOUBLE, `DEPOT_OPENING_STOCK` DECIMAL(38,14), `DEPOT_NET_STOCK_CUMM` DOUBLE, `DEPOT_CLOSING_INVENTORY` DOUBLE, `QUANTITY_AFTER_CURING` DECIMAL(34,14), `PLANT_DAILY_NET_DISPATCHABLE_STOCK` DOUBLE, `PLANT_NET_DISPATCHABLE_STOCK_CUMM` DOUBLE, `PLANT_CLOSING_DISPATCHABLE_STOCK` DOUBLE, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_DAILY_SEASONAL_PLAN'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_depot_monthly_targets` (`SALE_PLAN` BIGINT, `CLOSING_INVENTORY` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_DEPOT_MONTHLY_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_depot_netloss` (`MOVEMENT_TYPE` STRING, `MATL_KEY` STRING, `MATL_DOC` STRING, `MATL_DOC_YEAR` STRING, `DOC_ITEM` STRING, `QTY_KEY` DECIMAL(13,3), `UNIT_WEIGHTS` DECIMAL(11,6), `TOTAL_UNIT_WEIGHTS` DECIMAL(25,9), `WEIGHTS_MT` DECIMAL(30,14), `NET_LOSS_MT` DECIMAL(30,14), `DATE_KEY` BIGINT, `PLANT_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `STORAGE_LOCATION_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/prod/pro/FACT/FACT_DEPOT_NETLOSS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_depot_yearly_targets` (`NET_LOSS_TO_SALE` DECIMAL(13,2), `FREIGHT_TARGET` BIGINT, `DATE_KEY` BIGINT, `PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_DEPOT_YEARLY_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_fpr_yearly_kpi_targets` (`FPR` STRING, `KPI` STRING, `TARGET` DECIMAL(13,2), `DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_FPR_YEARLY_KPI_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_global_yearly_kpi_targets` (`KPI` STRING, `TARGET` DECIMAL(13,2), `DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_GLOBAL_YEARLY_KPI_TARGETS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_plant_daily_targets` (`PRODUCTION` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_PLANT_DAILY_TARGETS'
# MAGIC )
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_plant_depot_capacity` (`CAPACITY` BIGINT, `PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_PLANT_DEPOT_CAPACITY'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_plant_monthly_freight_targets` (`DISPATCH_TYPE` STRING, `VALUE` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_PLANT_MONTHLY_FREIGHT_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_plant_monthly_targets` (`STC_PLAN` BIGINT, `SALE_PLAN` BIGINT, `CLOSING_INVENTORY` BIGINT, `PLANT_KEY` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_PLANT_MONTHLY_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_stc_targets` (`STC_PLAN` BIGINT, `DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `PLANT_KEY` BIGINT, `DEPOT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_LOGISTICS_STC_TARGETS'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_sales_invoice` (`INVOICE_ID` STRING, `INVOICE_LINE_ID` STRING, `QUANTITY` DECIMAL(13,3), `QUANTITY_EA` DECIMAL(13,3), `STORAGE_LOC` STRING, `VOLUME_UNIT` STRING, `GROSS_WEIGHT` DECIMAL(20,8), `ITEM_CREDIT_PRICE` DECIMAL(11,2), `NET_VALUE` DECIMAL(15,2), `TAX_AMT` DECIMAL(13,2), `WEIGHT_UNIT` STRING, `DOC_CRCY` STRING, `BILLING_TYPE` STRING, `VEHICLE_NO` STRING, `LR_NO` STRING, `DRIVER_CONT_NO` STRING, `WAYBILL_NO` STRING, `REGION` STRING, `VOLUME` DECIMAL(15,3), `BUSINESS_PLACE` STRING, `COMPANY_CODE` STRING, `EXCISE_DUTY_DATE` DATE, `EXCISE_DUTY_NUM` STRING, `DISTRICT` STRING, `ORDER_TYPE` STRING, `CUST_TYPE` STRING, `PSTLZ` STRING, `INCO1` STRING, `INCO2` STRING, `ASSESSIBLE_VALUE2` DECIMAL(34,2), `SECDRY_FREIGHT` DECIMAL(25,2), `TRADE_DIS` DECIMAL(33,2), `KERALA_DISC` DECIMAL(33,2), `KERALA_DISC_RATE` DECIMAL(26,6), `EXCISE_CONDITIONS` DECIMAL(26,6), `ENTRY_TAX_PERC` DECIMAL(26,6), `CST_PERC` DECIMAL(26,6), `VAT_PERC` DECIMAL(26,6), `ADDL_TAX_PERC` DECIMAL(26,6), `TCS_PERC` DECIMAL(26,6), `ORISSA_ENTRY_TAX_PERC` DECIMAL(26,6), `STATE_SEC_TAX_PERC` DECIMAL(26,6), `BASE_PRICE_DISC` DECIMAL(26,6), `RATE_DIFF` DECIMAL(25,6), `OCEAN_AIR_FREIGHT` DECIMAL(38,7), `PACKING_HIL_EXPORT` DECIMAL(38,7), `FOB_VALUE` DECIMAL(38,7), `ZCMP` DECIMAL(38,7), `TAXABLE_TURNOVER` DECIMAL(38,7), `CGST_PERC` DECIMAL(26,6), `CGST_AMNT` DECIMAL(33,2), `SGST_PERC` DECIMAL(26,6), `SGST_AMNT` DECIMAL(33,2), `IGST_PERC` DECIMAL(26,6), `IGST_AMNT` DECIMAL(33,2), `UGST_PERC` DECIMAL(26,6), `UGST_AMNT` DECIMAL(33,2), `BASE_PRICE_HIL` DECIMAL(33,2), `BASE_PRICE` DECIMAL(25,2), `FREIGHT_HIL` DECIMAL(33,2), `FREIGHT_ZF02` DECIMAL(33,2), `FREIGHT_ZF01` DECIMAL(33,2), `TOTAL_FREIGHT` DECIMAL(33,2), `MULTIPLICATION_FACTOR` DECIMAL(33,2), `INSURANCE` DECIMAL(23,2), `MRP` DECIMAL(23,2), `PF_ADDL_DISC` DECIMAL(25,2), `LOGISTICS_SUPPORT` DECIMAL(25,2), `PF_CD_ON_BILLING` DECIMAL(25,2), `ORC` DECIMAL(23,2), `PF_PRICE_DIFF` DECIMAL(23,2), `ZOD1` DECIMAL(23,2), `ZOD2` DECIMAL(23,2), `WP_ADDL_DISC` DECIMAL(23,2), `WP_PRICE_DIFF` DECIMAL(23,2), `WP_CD_ON_BILLING` DECIMAL(23,2), `ZRPB` DECIMAL(23,2), `ZRPC` DECIMAL(23,2), `ZBPB_PU` DECIMAL(38,14), `SALES_ORG_TYPE` STRING, `TOTAL_SALES_VALUE` DECIMAL(35,2), `TRANS_TYPE` STRING, `TRANSPORTERID` STRING, `GEO_KEY` BIGINT, `GEO_KEY_SHIP` BIGINT, `DIVISION_KEY` BIGINT, `PLANT_KEY` BIGINT, `SALES_ORG_KEY` BIGINT, `DIST_CHANNEL_KEY` BIGINT, `SALES_TYPE_KEY` BIGINT, `DATE_CREATED_KEY` BIGINT, `PAYER_CUST_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `PAYER_ADDR_KEY` BIGINT, `SALES_PER_KEY` BIGINT, `BILLING_DATE_KEY` BIGINT, `SOLD_TO_PARTY_KEY` BIGINT, `AGENT_ADDR_KEY` BIGINT, `AGENT_CUST_KEY` BIGINT, `BILLTO_ADDR_KEY` BIGINT, `BILLTO_CUST_KEY` BIGINT, `SOLDTO_ADDR_KEY` BIGINT, `SHIPTO_ADDR_KEY` BIGINT, `SHIPTO_CUST_KEY` BIGINT, `PRODUCT_LINE_KEY` BIGINT, `FIRST_TIME_SALES_KEY` BIGINT, `LAST_EXECUTED_TIME` TIMESTAMP, `INVOICE_STATUS` STRING)
# MAGIC USING DELTA
# MAGIC OPTIONS (
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT_SALES_INVOICE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC select sum(GROSS_WEIGHT) from `pro_prod`.`fact_sales_invoice` where INVOICE_STATUS != 'CANCELLED'

# COMMAND ----------

# MAGIC %sql
# MAGIC select sum(GROSS_WEIGHT) from `pro_dev`.`fact_sales_invoice` where INVOICE_STATUS != 'CANCELLED'

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT A.* FROM `pro_dev`.`FACT_LOGISTICS_STO` as A WHERE NOT EXISTS 
# MAGIC    (SELECT * FROM `pro_prod`.`FACT_LOGISTICS_STO` as B WHERE B.INVOICE_NO = A.INVOICE_NO AND B.INVOICE_LINE_ID = A.INVOICE_LINE_ID)

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_security_deposit` (`CUSTOMER_KEY` BIGINT, `SNAPSHOT_DATE_KEY` BIGINT, `LAST_EXECUTED_TIME` TIMESTAMP, `MONTH` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT_SECURITY_DEPOSIT'
# MAGIC )
# MAGIC PARTITIONED BY (MONTH)

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC CREATE TABLE `pro_dev`.`fact_stock_movement` (`INVOICE_DATE` DATE, `INVOICE_NO` STRING, `INVOICE_LINE_ID` STRING, `NET_VALUE` DECIMAL(13,2), `CHALLAN_NO` STRING, `IGST_RATE` DECIMAL(26,6), `CGST_RATE` DECIMAL(26,6), `SGST_RATE` DECIMAL(26,6), `REC_QUANTITY` DECIMAL(25,3), `SALES_UNIT_INFORMATION` STRING, `SUPP_QTY_MT` DECIMAL(32,11), `BASE_UNIT_OF_MEASURE_INFORMATION` STRING, `PO_NUMBER` STRING, `PO_ITEM` STRING, `FREIGHT` DECIMAL(38,6), `TRANSPORTER_CODE` STRING, `SUPP_QUANTITY` DECIMAL(13,3), `REC_QUANTITY_MT` DECIMAL(38,6), `SUPPLYING_PLANT_KEY` BIGINT, `SUPPLYING_DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `RECEIVING_PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT/FACT_STOCK_MOVEMENT'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC
# MAGIC CREATE TABLE `pro_dev`.`fact_vendor_rating` ( `INSPECTION_LOT` STRING, `QUALITY_SCORE` DECIMAL(38,18),`REMARKS` STRING ,`DATE_CREATED_KEY` BIGINT,`PLANT_KEY` BIGINT,`VENDOR_KEY` BIGINT,`MATERIAL_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT_VENDOR_RATING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`FACT_OVERDUES_CRETERIA` ( `SBU` STRING,`OVERDUE_PERIOD_START_IN_DAYS` INT,`PRODUCT_LINE_KEY` BIGINT,`SALES_TYPE_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT_OVERDUES_CRETERIA'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`OVERDUES_CRETERIA` (`SBU` STRING,`PRODUCT_LINE` STRING,`SALE_TYPE` STRING,`OVERDUE_PERIOD_START_IN_DAYS` INT,`LAST_UPDATED_DT_TS` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/OVERDUES_CRETERIA'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`fact_logistics_sto` (`INVOICE_DATE` DATE, `INVOICE_NO` STRING, `INVOICE_LINE_ID` STRING, `NET_VALUE` DECIMAL(13,2), `CHALLAN_NO` STRING, `IGST_RATE` DECIMAL(26,6), `CGST_RATE` DECIMAL(26,6), `SGST_RATE` DECIMAL(26,6), `REC_QUANTITY` DECIMAL(25,3), `SALES_UNIT_INFORMATION` STRING, `SUPP_QTY_MT` DECIMAL(32,11), `BASE_UNIT_OF_MEASURE_INFORMATION` STRING, `PO_NUMBER` STRING, `PO_ITEM` STRING, `FREIGHT` DECIMAL(38,6), `TRANSPORTER_CODE` STRING, `SUPP_QUANTITY` DECIMAL(13,3), `REC_QUANTITY_MT` DECIMAL(38,6), `TRANS_TYPE` STRING, `LAST_EXECUTED_TIME` STRING, `SUPPLYING_PLANT_KEY` BIGINT, `SUPPLYING_DATE_KEY` BIGINT, `MATERIAL_KEY` BIGINT, `RECEIVING_PLANT_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT_LOGISTICS_STO'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`FACT_PF_MATERIAL_VARIANCE` (`PRODUCTION_QTY_KGS` DECIMAL(37,9),`PRODUCTION_VALUE` DECIMAL(25,2),`COMPONENT_CONSUMPTION_QTY_KGS` DECIMAL(37,9),`COMPONENT_CONSUMPTION_VALUE` DECIMAL(25,2),`RM_RATE_PER_KG` DECIMAL(38,6),`STD_QTY_REQUIRED_KGS` DECIMAL(25,9),`STD_BOM_FOR_100_KGS` DECIMAL(38,9),`STD_COMPONENT_REQUIRED_VALUE` DECIMAL(38,6),`TARGET_PRICE` DECIMAL(38,9),`QTY_VARIANCE` DECIMAL(38,9),`RATE_VARIANCE` DECIMAL(38,9),`PLANT_KEY` BIGINT,`MATERIAL_KEY` BIGINT,`COMPONENT_KEY` BIGINT,`DATE_CREATED_KEY` BIGINT)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/FACT_PF_MATERIAL_VARIANCE'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`PUTYY_MIS_GL_MASTER` (`GL_GROUP` STRING,`GL_CODE` STRING,`GL_DESCRIPTION` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/PUTYY_MIS_GL_MASTER'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`GL_SEGMENT_MAPPING` (`PARTICULARS` STRING,`SEGEMNT` STRING,`GL_ACCOUNT_ID` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/GL_SEGMENT_MAPPING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE `pro_dev`.`CUST_PAYMENT_OUTSTANDING` (`KUNNR` STRING,`PERNR` STRING,`PSTLZ` STRING,`sales_type` STRING,`product_line` STRING,`SALES_ORG` STRING,`0_to_15_days` DECIMAL(38,2),`106_to_120_days` DECIMAL(38,2),`121_to_135_days` DECIMAL(38,2),`136_to_150_days` DECIMAL(38,2),`151_to_165_days` DECIMAL(38,2),`166_to_180_days` DECIMAL(38,2),`16_to_30_days` DECIMAL(38,2),`181_to_195_days` DECIMAL(38,2),`196_to_210_days` DECIMAL(38,2),`211_to_225_days` DECIMAL(38,2),`226_to_240_days` DECIMAL(38,2),`241_to_255_days` DECIMAL(38,2),`256_to_270_days` DECIMAL(38,2),`271_to_285_days` DECIMAL(38,2),`286_to_300_days` DECIMAL(38,2),`301_to_315_days` DECIMAL(38,2),`316_to_330_days` DECIMAL(38,2),`31_to_45_days` DECIMAL(38,2),`331_to_345_days` DECIMAL(38,2),`346_to_360_days` DECIMAL(38,2),`361_to_390_days` DECIMAL(38,2),`391_to_420_days` DECIMAL(38,2),`421_to_450_days` DECIMAL(38,2),`451_to_480_days` DECIMAL(38,2),`46_to_60_days` DECIMAL(38,2),`481_to_510_days` DECIMAL(38,2),`511_to_540_days` DECIMAL(38,2),`541_to_570_days` DECIMAL(38,2),`571_to_600_days` DECIMAL(38,2),`601_to_630_days` DECIMAL(38,2),`61_to_75_days` DECIMAL(38,2),`631_to_660_days` DECIMAL(38,2),`661_to_690_days` DECIMAL(38,2),`691_to_720_days` DECIMAL(38,2),`76_to_90_days` DECIMAL(38,2),`91_to_105_days` DECIMAL(38,2),`grtr_than_720_days` DECIMAL(38,2),`snapshot_date` STRING,`sales_org_type` STRING,`last_executed_time` STRING,`last_executed_date` date,`DISTRICT` STRING,`SALES_GROUP` STRING,`STATE` STRING,`ZONE` STRING,`COUNTRY` STRING,`CUSTOMER_SALES_TYPE` STRING,`CUSTOMER_SBU` STRING,`CUSTOMER_PRODUCT_LINE` STRING,`CUSTOMER_POSTAL_CODE` STRING,`CUSTOMER_SALES_ORG` STRING,`CUST_DISTRICT` STRING,`CUST_SALES_GROUP` STRING,`CUST_STATE` STRING,`CUST_ZONE` STRING,`CUST_COUNTRY` STRING)
# MAGIC USING PARQUET
# MAGIC OPTIONS (
# MAGIC   `compression` 'snappy',
# MAGIC   path 'dbfs:/mnt/bi_datalake/dev/pro/CUST_PAYMENT_OUTSTANDING'
# MAGIC )

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from `pro_dev`.`CUST_PAYMENT_OUTSTANDING`
